### ISSUE TITLE
what - im on 1.13 spigot

### ISSUE THREAD

**Issue by MrOller0** [ViaVersion/ViaVersion#2792] opened 2022-01-07 10:53 UTC
### `/viaversion dump` Output

a

### Console Error

![image](https://user-images.githubusercontent.com/89196230/148533525-e7d436a6-0b3f-4898-94a7-2c56b5f83e53.png)

### Bug Description

what is is

### Steps to Reproduce

help me

### Expected Behavior

a

### Additional Server Info

a

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment] 2022-01-07 10:55
Don't use 1.13.0. Duplicate of https://github.com/ViaVersion/ViaVersion/issues/2383

**Closed by kennytv** 2022-01-07 10:55 UTC
Labels: Unconfirmed

**Comment by MrOller0** [comment] 2022-01-07 10:58
> Don't use 1.13.0. Duplicate of #2383

what?

**Comment by MrOller0** [comment] 2022-01-07 10:58
why?

**Comment by kennytv** [comment] 2022-01-07 11:00
The linked issue is the bug you're experiencing, but we're unlikely to fix it, since there's no reason for you to use 1.13.0 instead of .1 or .2 and the fix isn't *too* easy.
