### ISSUE TITLE
got kick everytime join

### ISSUE THREAD

**Issue by KILLERBOSS1475** [ViaVersion/ViaVersion#2663] opened 2021-08-14 10:49 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/c8af3ac328b90107c730af3cc8c720f2800e4d5ecc2fa002f61fa22813856c1f

### Console Error

```
Put the paste.gg link or text here.
```
[12:45:01 WARN]: [ViaVersion] ERROR IN Protocol1_16_4To1_17 IN REMAP OF UPDATE_LIGHT (0x25)
[12:45:01 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[12:45:01 WARN]: {Type: byte[], Data: [Pair{Type|VarInt, 8}, Pair{Type|VarInt, 15}, Pair{Type|Boolean, true}, Pair{Type|VarInt, 992}, Pair{Type|VarInt, 496}, Pair{Type|VarInt, 31}, Pair{Type|VarInt, 527}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$4 (Anonymous), Packet ID: 35}
[12:45:01 WARN]: Actual Error: 
[12:45:01 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:45:01 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:45:01 WARN]:        at NexEngine.jar//su.nexmedia.engine.nms.packets.PacketManager$1.write(PacketManager.java:112)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:45:01 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:45:01 WARN]:        at WarpSystem_v5.0.4-free.jar//de.codingair.warpsystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:72)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:45:01 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:45:01 WARN]:        at WarpSystem_v5.0.4-free.jar//de.codingair.warpsystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:72)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[12:45:01 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[12:45:01 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[12:45:01 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[12:45:01 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[12:45:01 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[12:45:01 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[12:45:01 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[12:45:01 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:45:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[12:45:01 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[12:45:01 WARN]: {Type: byte[], Data: [Pair{Type|VarInt, 8}, Pair{Type|VarInt, 15}, Pair{Type|Boolean, true}, Pair{Type|VarInt, 992}, Pair{Type|VarInt, 496}, Pair{Type|VarInt, 31}, Pair{Type|VarInt, 527}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$4 (Anonymous), Packet ID: 35}
[12:45:01 WARN]: Actual Error: 
[12:45:01 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(42) + length(1) exceeds writerIndex(42): PooledUnsafeDirectByteBuf(ridx: 42, widx: 42, cap: 256)
[12:45:01 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[12:45:01 WARN]:        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:40)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.api.type.types.ByteArrayType.read(ByteArrayType.java:42)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.api.type.types.ByteArrayType.read(ByteArrayType.java:29)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:125)
[12:45:01 WARN]:        at ViaBackwards-4.0.1.jar//com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$4.writeLightArrays(BlockItemPackets1_17.java:183)
[12:45:01 WARN]:        at ViaBackwards-4.0.1.jar//com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$4.lambda$registerMap$0(BlockItemPackets1_17.java:162)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[12:45:01 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
[12:45:01 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:45:01 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268)
[12:45:01 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:45:01 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:45:01 WARN]:        at NexEngine.jar//su.nexmedia.engine.nms.packets.PacketManager$1.write(PacketManager.java:112)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:45:01 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:45:01 WARN]:        at WarpSystem_v5.0.4-free.jar//de.codingair.warpsystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:72)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:45:01 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:45:01 WARN]:        at WarpSystem_v5.0.4-free.jar//de.codingair.warpsystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:72)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[12:45:01 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[12:45:01 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[12:45:01 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[12:45:01 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[12:45:01 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[12:45:01 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[12:45:01 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[12:45:01 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:45:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[12:45:01 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[12:45:01 WARN]: {Type: byte[], Data: [Pair{Type|VarInt, 8}, Pair{Type|VarInt, 15}, Pair{Type|Boolean, true}, Pair{Type|VarInt, 992}, Pair{Type|VarInt, 496}, Pair{Type|VarInt, 31}, Pair{Type|VarInt, 527}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$4 (Anonymous), Packet ID: 35}
[12:45:01 WARN]: Actual Error: 
[12:45:01 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:45:01 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:45:01 WARN]:        at NexEngine.jar//su.nexmedia.engine.nms.packets.PacketManager$1.write(PacketManager.java:112)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:45:01 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:45:01 WARN]:        at WarpSystem_v5.0.4-free.jar//de.codingair.warpsystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:72)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:45:01 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:45:01 WARN]:        at WarpSystem_v5.0.4-free.jar//de.codingair.warpsystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:72)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[12:45:01 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[12:45:01 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[12:45:01 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[12:45:01 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[12:45:01 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[12:45:01 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[12:45:01 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[12:45:01 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:45:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[12:45:01 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[12:45:01 WARN]: {Type: byte[], Data: [Pair{Type|VarInt, 8}, Pair{Type|VarInt, 15}, Pair{Type|Boolean, true}, Pair{Type|VarInt, 992}, Pair{Type|VarInt, 496}, Pair{Type|VarInt, 31}, Pair{Type|VarInt, 527}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$4 (Anonymous), Packet ID: 35}
[12:45:01 WARN]: Actual Error: 
[12:45:01 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(42) + length(1) exceeds writerIndex(42): PooledUnsafeDirectByteBuf(ridx: 42, widx: 42, cap: 256)
[12:45:01 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[12:45:01 WARN]:        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:40)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.api.type.types.ByteArrayType.read(ByteArrayType.java:42)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.api.type.types.ByteArrayType.read(ByteArrayType.java:29)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:125)
[12:45:01 WARN]:        at ViaBackwards-4.0.1.jar//com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$4.writeLightArrays(BlockItemPackets1_17.java:183)
[12:45:01 WARN]:        at ViaBackwards-4.0.1.jar//com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$4.lambda$registerMap$0(BlockItemPackets1_17.java:162)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[12:45:01 WARN]:        at ViaVersion-4.0.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[12:45:01 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
[12:45:01 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:45:01 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268)
[12:45:01 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:45:01 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:45:01 WARN]:        at NexEngine.jar//su.nexmedia.engine.nms.packets.PacketManager$1.write(PacketManager.java:112)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:45:01 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:45:01 WARN]:        at WarpSystem_v5.0.4-free.jar//de.codingair.warpsystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:72)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:45:01 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:45:01 WARN]:        at WarpSystem_v5.0.4-free.jar//de.codingair.warpsystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:72)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[12:45:01 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[12:45:01 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[12:45:01 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[12:45:01 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[12:45:01 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[12:45:01 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[12:45:01 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[12:45:01 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[12:45:01 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[12:45:01 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:45:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[12:45:01 INFO]: coolguy009 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: byte[], Data: [Pair{Type|VarInt, 8}, Pair{Type|VarInt, 15}, Pair{Type|Boolean, true}, Pair{Type|VarInt, 992}, Pair{Type|VarInt, 496}, Pair{Type|VarInt, 31}, Pair{Type|VarInt, 527}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$4 (Anonymous), Packet ID: 35}
Actual Error: 
[12:45:01 INFO]: coolguy009 left the game

### Bug Description

some of player joined server and automaticly got kick bc thouse errors

### Steps to Reproduce

join server
and instantly got kick

### Expected Behavior

it should not get kick or this error should not showd up

### Additional Server Info

i use spigot

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2021-08-14 10:49
![Platform: git-Paper-169 (MC: 1.17.1)](https://img.shields.io/badge/Platform-git--Paper--169%20%28MC%3A%201.17.1%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-14%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 10 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-10%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment] 2021-08-14 10:50
Duplicate of #2662

**Closed by kennytv** 2021-08-14 10:50 UTC
Labels: Unconfirmed
