### ISSUE TITLE
ERROR IN Protocol1_13To1_12_2 IN REMAP OF CHUNK_DATA (0x20)

### ISSUE THREAD

**Issue by LoXR** [ViaVersion/ViaVersion#1868] opened 2020-07-01 06:23 UTC
**Describe the bug, provide any errors**
https://mcpaste.io/575773d9b0cb4390

**How can we reproduce it?**
1. Join server any version'
2. Try go to an area that seems to be 1.13+ items on 1.12 server
3. Disconnect

**Expected behaviour**
It was working before, but unsure what and why this has occured.

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/03f9d2ecbef78d0ba297c57b27362a496686a6770bd2ca3b6068ca518cbacd5a

**Additional server info**
No Proxy, server version: git-Paper-1618 (MC: 1.12.2)

**Comment by LoXR** [comment] 2020-07-01 06:28
Will add in aswell, I was on 1.14.4, and I wanted to test 1.12.2 and seems being on the correct client version fixed my issue.

**Comment by KennyTV** [comment] 2020-07-01 06:43
Duplicate of #1860

**Closed by KennyTV** 2020-07-01 06:43 UTC
