### ISSUE TITLE
ViaVersion 4.4.1 erroneously removes some descriptive comments from `config.yml`.

### ISSUE THREAD

**Issue by akemin-dayo** [ViaVersion/ViaVersion#3052] opened 2022-07-28 17:39 UTC
### `/viaversion dump` Output
https://dump.viaversion.com/9a7f89387795d903e65adab61063b914f099e9c3907547d590299f75f6602c60

---

### Bug Description
ViaVersion 4.4.1 erroneously removes some descriptive comments from `config.yml`.

Here's a partial diff of the affected area.

```diff
diff --git a/plugins/ViaVersion/config.yml b/plugins/ViaVersion/config.yml
index b1dd938..b46d049 100644
--- a/plugins/ViaVersion/config.yml
+++ b/plugins/ViaVersion/config.yml
@@ -123,56 +123,33 @@ resource-pack-1_17-prompt: ''
 # Only disable this if you know what you are doing.
 cache-1_17-light: true
 # 
-# ----------------------------------------------------------#
-#             1.9+ CLIENTS ON 1.8 SERVERS OPTIONS          #
-# ----------------------------------------------------------#
-# 
-# No collide options, these allow you to configure how collision works.
-# Do you want us to prevent collision?
+# 1.19 chat type formats used for 1.19.1+ clients.
+chat-types-1_19:
+  chat.type.text: <%s> %s
+  chat.type.announcement: '[%s] %s'
+  commands.message.display.incoming: '%s whispers to you: %s'
+  chat.type.team.text: '%s <%s> %s'
+  chat.type.emote: '* %s %s'
 prevent-collision: true
-# If the above is true, should we automatically team players until you do?
 auto-team: true
-# When enabled if certain metadata can't be read we won't tell you about it
 suppress-metadata-errors: false
-# When enabled 1.9+ will be able to block by using shields
 shield-blocking: true
-# If this setting is active, the main hand is used instead of the off hand to trigger the blocking of the player.
-# With the main hand the blocking starts way faster.
-# (Requires "show-shield-when-sword-in-hand" to be disabled)
 no-delay-shield-blocking: false
-# If this setting is active, the shield will appear immediately for 1.9+ when you hold a sword in your main hand.
-# The shield disappears when you switch to another item.
-# (Requires "shield-blocking" to be enabled)
 show-shield-when-sword-in-hand: false
-# Enable player tick simulation, this fixes eating, drinking, nether portals.
 simulate-pt: true
-# Should we use nms player to simulate packets, (may fix anti-cheat issues)
 nms-player-ticking: true
-# Should we patch boss bars so they work? (Default: true, disable if you're having issues)
 bossbar-patch: true
-# If your boss bar flickers on 1.9+, set this to 'true'. It will keep all boss bars on 100% (not recommended)
 bossbar-anti-flicker: false
-# This will show the new effect indicator in the top-right corner for 1.9+ players.
 use-new-effect-indicator: true
-# Show the new death messages for 1.9+ on the death screen
 use-new-deathmessages: true
-# Should we cache our items, this will prevent server from being lagged out, however the cost is a constant task caching items
 item-cache: true
-# Patch the anti xray to work on 1.9+ (If your server is 1.8) This can cost more performance, so disable it if you don't use it.
 anti-xray-patch: false
-# Should we replace extended pistons to fix 1.10.1 (Only on chunk load)
 replace-pistons: false
-# What id should we replace with, default is air. (careful of players getting stuck standing on them)
 replacement-piston-id: 0
-# Fix 1.9+ clients not rendering the far away chunks and improve chunk rendering when moving fast (Increases network usage and decreases client fps slightly)
 chunk-border-fix: true
-# Force the string -> json transform
 force-json-transform: false
-# Minimize the cooldown animation in 1.8 servers
 minimize-cooldown: true
-# Allows 1.9+ left-handedness (main hand) on 1.8 servers
 left-handed-handling: true
-# Get the world names which should be returned for each vanilla dimension
 map-1_16-world-names:
   overworld: minecraft:overworld
   nether: minecraft:the_nether
```

---

### Steps to Reproduce
1. Start a server with ViaVersion 4.4.1 present.
2. There is no step 2.

---

### Expected Behavior
The descriptive comments in `config.yml` should not have been removed.

---

### Checklist
- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by HowardZHY** [comment] 2022-07-29 16:17
just block 1.19.1 and ignore it

**Comment by creeper123123321** [comment] 2022-07-30 18:26
duplicate of #2614

**Closed** 2022-08-01 10:30 UTC
Labels: Bug
