### ISSUE TITLE
Joining error when using a 1.20.2 or higher client

### ISSUE THREAD

**Issue by LeonTG** [ViaVersion/ViaVersion#3642] opened 2024-01-11 18:45 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/1407a987e081eca276257ad09a6d2b24ca8235e163846faeb8b918cf6711a3f8

### Console Error

There are no errors, but this is what appears in console

```
[18:32:24 INFO]: UUID of player LeonTG is 8b2b2e07-b694-4bd0-8f1b-ba99a267be41
[18:32:24 INFO]: (») LeonTG
[18:32:24 INFO]: LeonTG[/<hidden>] logged in with entity id 1723 at ([spawn]0.5, 31.0, 0.5)
[18:32:24 INFO]: LeonTG lost connection: Disconnected
[18:32:24 INFO]: («) LeonTG
```

### Bug Description

Whenever I join my 1.19 server with a 1.20.2, 1.20.3 or 1.20.4 client, I get this error: https://gyazo.com/f0060445448aaaf513281b4bd7bfa3d2

HOWEVER! This only happens when trying to connect to my servers on the BungeeCord network!

When using the exact same setup, but changing the server to not be on the BungeeCord, then joining works perfectly

And yes, I only got ViaVerison on backend servers, as it says to do

### Steps to Reproduce

1. Have a 1.19 server behind a BungeeCord proxy
2. Join on 1.20.2
3. It wont let you join

idk how to say it better haha, its such a strange issue

### Expected Behavior

I expect to be able to join with 1.20.2 or higher and not be kicked with an error message, the same way it works fine when not using bungee

### Additional Server Info

As said above, yes I do have BungeeCord, as thats the only setup it appears on

I do have a Paper fork as seen in the dump, however it does not mess with Packets and I can say that for sure as I am the one who manages the fork and know what I have changed from regular Paper, which is just adding some API I want to have

And also like I said, it works fine when not on BungeeCord, so that should also show that it probs got nothing to do with my setup

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2024-01-11 18:45
![Platform: git--Arctic--%223015df6%22%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Arctic--%223015df6%22%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 34 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-34%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by LeonTG** [comment] 2024-01-11 18:47
Here is the dump that isn't 34 commits behind, must have sent the wrong link when testing different versions, my bad

https://dump.viaversion.com/40675e6d68a30b691ca63e72b623ac43330fd6b0baef6c9daa5c5faf151689c1

**Comment by Barvalg** [comment] 2024-01-11 18:47
![Platform: git--Arctic--%223015df6%22%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Arctic--%223015df6%22%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment] 2024-01-11 18:50
Can you update bungeecord to latest version *(in case you haven't yet)* ?, Also i may be certain that if it's not bungee then either third-party plugin or the unrecognizable spigot fork is causing unexpected behavior.

**Comment by LeonTG** [comment] 2024-01-11 19:01
> Can you update bungeecord to latest version _(in case you haven't yet)_ ?, Also i may be certain that if it's not bungee then either third-party plugin or the unrecognizable spigot fork is causing unexpected behavior.

My BungeeCord is on the latest version 

and I have just now tried it without my custom plugin and custom paper fork, and the same issue persists

You can see the new dump here: https://dump.viaversion.com/0f99015b6d4f37f739bf96477fc32ab886db0bebaacd9e4730f309c6c23c3dfb

So this is now a regular Paper 1.19 jar, with only WorldEdit, ProtocolLib and ViaVersion, 2 very common plugins to have, and the issue still happens

**Comment by Barvalg** [comment] 2024-01-11 19:01
![Platform: git--Paper--81%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Paper--81%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment] 2024-01-11 19:02
Does this persist on 1.19.4 paper? if yes; something isn't right.

**Comment by LeonTG** [comment] 2024-01-11 19:04
1.19.4, same issue

Dump: https://dump.viaversion.com/686c2f0e5aa410ef3d1d2a926bb1479cf843727bf0bd5d42deea19a413364908

**Comment by Barvalg** [comment] 2024-01-11 19:04
![Platform: git--Paper--550%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--550%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment] 2024-01-11 19:11
Did an investigation and could not reproduce your problem:

![mc](https://github.com/ViaVersion/ViaVersion/assets/68134602/e8a72590-71ef-4644-a280-49cfe8c1d484)

**Comment by LeonTG** [comment] 2024-01-11 19:17
That is very strange, I don't see a difference here

![2024-01-11_20 14 04](https://github.com/ViaVersion/ViaVersion/assets/8997490/9fd3989c-7948-4b6c-93c1-85977ff2f2e5)

**Comment by Kichura** [comment] 2024-01-11 19:21
Either a sudden hiccup occurred in bungee itself or something else caused the errors to appear, you might wanna investigate this furtherly to see what caused your problem to happen in first place.

**Comment by LeonTG** [comment] 2024-01-11 19:23
This has been happening ever since 1.20.2 was released in September 2023, and I've been updating ViaVersion and BungeeCord since then hoping it would get fixed but still having the error

so its not a sudden thing, it was there from the day the update was released

**Comment by LeonTG** [comment] 2024-01-11 21:23
Ok I got an update

After a while of trying to figure this out, I noticed 1 difference in our 2 screenshots, and that was the server brand naming on the F3 screen, where I have a custom one that I forgot I had

I turned it back to regular server branding, and it seemed to have fixed the issue

So the issue was something with server branding not being done correctly with BungeeCord after 1.20.2, which is probably an issue with Bungee and not ViaVersion

Thank you for your help @Kichura, sorry for the false-report haha, I really thought this was ViaVersion acting up

**Comment by Kichura** [comment] 2024-01-11 21:31
Closing this since this issue is declared resolved.

**Closed by Kichura** 2024-01-11 21:31 UTC
Labels: Can't Reproduce
