### ISSUE TITLE
PR #2934 broke Velocity support

### ISSUE THREAD

**Issue by Hyronymos1337** [ViaVersion/ViaVersion#2945] opened 2022-06-11 23:03 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/d01a915c751fcd886d8507448d00e8c27855b50df56fa1acba60cc540bf354b3

### Console Error

No Erros

### Bug Description

Since PR #2934 , you no longer get messages sent by Velocity

### Steps to Reproduce

1. Newest Velocity
2. A Velocity Plugin that sends message to Clients

### Expected Behavior

---

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2022-06-11 23:03
![Platform: git--NachoSpigot--%225655b72%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--NachoSpigot--%225655b72%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Pantera07** [comment] 2022-06-12 12:37
I have confirmed this. Reproduceable

**Comment by totKing** [comment] 2022-06-14 18:36
https://github.com/ViaVersion/ViaVersion/commit/40f5cb6e71e54f21c6873caba22283fa95f20e2f - Since commit the error exists

**Comment by MenschenToaster** [comment] 2022-06-25 08:18
This is fixed on the newest velocity dev build.

**Closed** 2022-06-30 07:44 UTC
Labels: Unconfirmed
