### ISSUE TITLE
GUI Bug - Fatal

### ISSUE THREAD

**Issue by FrancyMak** [ViaVersion/ViaVersion#2735] opened 2021-11-21 08:58 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/ff62a0490d6b9f4cb8f074cd54dfad60bd3e96b82d243cddde184acfecb4fb05

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

After the update to 1.17, with the relative update of the via version and backwards, I encountered this problem which is quite serious, as by exiting and re-entering the server the item is totally bugged, making it possible to use it effectively.

https://streamable.com/53iws3

At first I thought it was paper, but when I tested 1.17.1 on the server, the bug was totally gone.

### Steps to Reproduce

1. Entering with, for example, 1.16.5
2. Open any kind of GUI, either deluxemenus or AureliumSkills and repeatedly try to grab the object from the GUI, either by clicking SHIFT or moving it with the mouse.
3. Some times it will only be visual, others it will leave you the object in the invetary

### Expected Behavior

The object should not even remain in the mouse.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2021-11-21 08:58
![Platform: git--Paper--388%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--388%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.0-1.18-pre5-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.1.0--1.18--pre5--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaBackwards(4.1.0-1.18-pre5-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.1.0--1.18--pre5--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment] 2021-11-21 09:00
Duplicate of https://github.com/ViaVersion/ViaBackwards/issues/389
This is not a dupe but a visual glitch, the reason you copied the item is because creative mode has full control over its inventory

**Closed by kennytv** 2021-11-21 09:00 UTC
Labels: Unconfirmed
