### ISSUE TITLE
Protocol1_13To1_12_2 IN REMAP OF CHAT_MESSAGE (0x0F) Error is still not fixed in the devbuild

### ISSUE THREAD

**Issue by Pace1337** [ViaVersion/ViaVersion#2429] opened 2021-04-10 22:11 UTC
### '/viaversion dump' Output

https://dump.viaversion.com/3a19698296edf0c991ccaf6aca276affdd9ac6edc6dd0fbd87082935df017fe6

### Console Error

https://haste.jartexnetwork.com/sifuxobabeyovuko.yaml

### Bug Description

https://youtu.be/Oy78s_3CSh8

### Steps to Reproduce

If you use an item name with \\\\\ inside it with and if you use show_item in main chat, people in version 1.16 will crash.

### Expected Behavior

You should not get kicked if you use the 1.16 version, this can be easily abused on any server.

### Additional Server Info

Hi, so I reported this earlier, and you have told me to update to the devbuild. The server is currently running "ViaVersion-3.3.0-21w14a" and this issue is still happening. We have no idea how to fix this, so if you guys got anything in mind of how to fix it it'd be great. If you need anything else from me to be tested reply below.

### Checklist

Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
I have included a ViaVersion dump.
If applicable, I have included a paste (**not a screenshot**) of the error.
I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment] 2021-04-11 08:23
Does that hover actually work? It just looks like invalid NBT to me (we'd still warn about it but try not to kick clients over it then)

**Comment by pacebesteu** [comment] 2021-04-11 11:15
Yeah. It displays for clients from 1.8 up to latest ViaVersion. But only people that play above 1.12.2 will crash. If you want, I can record a simple video for you to make things such easier.

**Comment by pacebesteu** [comment] 2021-04-11 11:25
Here you go: https://youtu.be/-L-UKzORRKc

**Comment by pacebesteu** [comment] 2021-04-11 11:26
Oh btw I used /rename to rename those items, but servers (like ours) have custom NameTags you can rename it to this and if they have {item} or [item] etc you can easily abuse this.

**Comment by KennyTV** [comment] 2021-04-11 11:37
Thank you, the next -dev build on the ci should at least not kick you and you can suppress warnings in the config. I can't promise this will be properly fixed anytime soon, tho.

**Comment by pacebesteu** [comment] 2021-04-11 13:08
Yeah I just tested it, it seems to be fixed in latest dev build. It does not kick you anymore, thanks a lot. Hopefully you can find a proper fix soon.

**Comment by erdann2** [comment] 2021-04-12 03:01
I have a problem i have a Network with Hub Version 1.8.8 and with Version 1.9.1 it saying error, apparently only with that version :( https://i.imgur.com/zh9sQ0u.png

**Comment by Pace1337** [comment] 2021-04-12 06:07
@erdann2 this is not the right place, create a new issue at https://github.com/ViaVersion/ViaVersion/issues within "New issue" green button and fill it out.

**Comment by KennyTV** [comment] 2021-05-22 16:15
Another error in this parsing:
```
[16:32:41] [Netty Epoll Server IO #0/WARN]: [ViaVersion] Error reading NBT in show_item:{id:spawn_egg,tag:{display:{Name:"Parrot",Lore:[a:"Hunger: 99",a:"Health: 20,00",a:"Опыт: 0,00",a:"A type: Parrot",a:"Skill tree: Ride"]}}}
[16:32:41] [Netty Epoll Server IO #0/WARN]: java.io.IOException: com.viaversion.viaversion.api.minecraft.nbt.StringTagParseException: Expected character ',' but got ':'(at position 50)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.minecraft.nbt.BinaryTagIO.readString(BinaryTagIO.java:194)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.data.ComponentRewriter1_13.handleHoverEvent(ComponentRewriter1_13.java:59)
```

**Comment by KennyTV** [comment] 2021-05-30 21:26
Confirmed to be a legacy server NBT serialization bug that even 1.8 clients simply mark as "Invalid item". As already said above, this no longer *kicks* players, but instead only sends a warnings to the console. Enabling `suppress-conversion-warnings` in the config will hide those as well - tho being invalid formatted nbt, it is out of scope for Via to fix.

**Closed by KennyTV** 2021-05-30 21:26 UTC
Labels: Bug, Legacy
