### ISSUE TITLE
Bug with Procosmetics

### ISSUE THREAD

**Issue by Cryptics1999** [ViaVersion/ViaVersion#1809] opened 2020-06-21 19:54 UTC
I logged into a server using the latest snapshot of viaversion 3.0.0 and when I logged into the server on 1.15.2 alot of stuff did not show as its supposed to as like some parts of armor not showing like this
![image](https://user-images.githubusercontent.com/67240914/85233670-578fc780-b408-11ea-86b4-f89dba022782.png)

The banners dont work as they are supposed to either.
![image](https://user-images.githubusercontent.com/67240914/85233717-bead7c00-b408-11ea-9388-e21d84e094fb.png)
This is supposed to be a swedish flag.

Steps to reproduce:
1: Get procosmetics on a 1.8.8 server
2: Get the snapshot I wrote earlier in the bug report.
3: Log on in 1.15.2 and use some of the items and see that armors and morphs do not move you like they are supposed to do from 1.8.8, Also some of the banners are not showed as the right banner.

ViaVersion Dump: https://dump.viaversion.com/542289e89dbba53451a5e983876b97bc5b75c216f78dda40bbbdc5cdd77846ab

Server info:
This is a bungeecord server, and the issue is with the ProCosmetic plugin.

ProCosmetics Link:
https://www.spigotmc.org/resources/procosmetics-185-cosmetics-treasurechests-eula-compliant-1-8-1-15-support.49106/

**Comment by KennyTV** [comment] 2020-06-21 19:59
Since the plugin is premium, we can't really investigate the issue, but at least for the armor issue it is very likely that the plugin simply used wrong armor slots in custom equipment packets. The 1.8 client didn't care if the slot was wrong and would simply put it in the correct one, whereas 1.9+ does not do that on its own.

Can you create a custom banner via a command (through an online banner generator or similar), test with 1.8 and 1.15, and report if you can give us a reproducable way of getting the issue? If so, also find our from what version onwards the issue starts happening

**Comment by File14** [comment] 2020-06-21 20:19
Fixed Miniature armor issue (incorrect armor slot on leggings and chestplate).

I do believe the banner issue is caused by ViaVersion as it working if the client has the same version as the server.

**Comment by KennyTV** [comment] 2020-06-21 20:43
Could you dump the serialized nbt of the banner?

**Comment by File14** [comment] 2020-06-21 21:30
Please watch this: https://i.gyazo.com/7a148cfa06439f8534244b1d74426604.gif
Code: `	ItemStack banner = new ItemStack(Material.BANNER);
		BannerMeta bannerMeta = (BannerMeta) banner.getItemMeta();
		bannerMeta.setBaseColor(DyeColor.BLUE);
		banner.setItemMeta(bannerMeta);
		player.setItemInHand(banner);
		player.getInventory().setHelmet(banner);`
{type=BANNER, meta=BANNER_META:{meta-type=BANNER, base-color=BLUE}}

**Comment by KennyTV** [comment] 2020-06-22 08:20
Thank you for the report, will be fixed with the next release.

**Closed by KennyTV** 2020-06-22 08:20 UTC
