### ISSUE TITLE
 Bug when a player reaches a certain chunk in the game with 1.13.2

### ISSUE THREAD

**Issue by dule0004** [ViaVersion/ViaVersion#2469] opened 2021-05-11 09:35 UTC
### '/viaversion dump' Output

https://dump.viaversion.com/0378a44f56c1a5c895497453936c490ec29567c78718d56c765409597d28875c

### Console Error

No console error

### Bug Description

Joining with 1.13.2 version to certain chunk. 
Crash report log: https://paste.ee/p/KNk6a
Minecraft crash screen: https://i.imgur.com/v2A4oHO.png

### Steps to Reproduce

1. Login to 1.13.2 client
2. Come to chunk

### Expected Behavior

That bug don't appear on 1.16.4

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Jo0001** [comment] 2021-07-18 12:43
I assume the issue is fixed in the meantime. In case its not, try to use the latest Via (4.0.2-Snapshot). If the issue then still occurs, feel free to open a new issue

**Closed by Jo0001** 2021-07-18 12:43 UTC
