### ISSUE TITLE
Massive lag caused by viaversion issue.

### ISSUE THREAD

**Issue by Yomamaeatstoes** [ViaVersion/ViaVersion#3218] opened 2023-02-19 02:51 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/2a43b455dd7db5366884697f1f20df0a67f62317dbf3739c793238debb2e6647

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/46cd6770043f4fb5831dd710af98663a

### Bug Description

I am not entirely sure what is happening here, but it causes massive lag!

### Steps to Reproduce

Honestly no idea

### Expected Behavior

no massive error with a ton of lag

### Additional Server Info

Paper 1.19.2

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2023-02-19 02:51
![Platform: git--Paper--307%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--Paper--307%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by F3F5** [comment] 2023-02-19 17:46
BUMP! I HAVE LAG https://timings.aikar.co/dev/?id=68557f313abe44de9bf81a17402df2ca

**Comment by FormallyMyles** [comment] 2023-02-19 17:53
Duplicate of https://github.com/ViaVersion/ViaVersion/issues/3197

**Closed by FormallyMyles** 2023-02-19 17:53 UTC
Labels: Unconfirmed
