### ISSUE TITLE
Kicked when using a loom.

### ISSUE THREAD

**Issue by spookymgmt** [ViaVersion/ViaVersion#3010] opened 2022-07-09 17:25 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/e148ea64a2b0afbaffe7ab538d2823a3cf4799903f7b91649f5585294b5f973d

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Client error 

The game crashed whilst container click
Error: java.lang.ArrayIndexOutOfBoundsException: Index 38 out of bounds for length 0
Exit Code: -1

### Steps to Reproduce

1. Place loom on 1.19 client
2. I tested with gray banner, flower_banner_pattern, and brown_dye.
3. Shift right click all items into loom = crash.

It's not just me either, not a single player on my server can use looms.

### Expected Behavior

Banner creation

### Additional Server Info

Velocity (latest)
Pufferfish (1.18.2)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2022-07-09 17:25
![Platform: git--Pufferfish--%228f05a00%22%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Pufferfish--%228f05a00%22%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment] 2022-07-09 17:28
Duplicate of https://github.com/ViaVersion/ViaVersion/issues/2938

**Closed by kennytv** 2022-07-09 17:28 UTC
Labels: Unconfirmed
