### ISSUE TITLE
Explosions cause ghost blocks

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#1454] opened 2019-09-15 02:02 UTC
Describe the bug, provide any errors
Any explosion will cause ghost blocks

How can we reproduce it?

Login on to ANY version
Blow stuff up and walk around, you will get caught in ghost blocks
Expected behaviour
There shouldnt be glitches

Screenshots

ViaVersion Dump:
https://dump.viaversion.com/50ee816cb992c6fda9e0c992a9593a3f91ad67c7a4344444a3b5ae07c772cd70

Additional server info
Bungeecord 1.14.4, paperspigot 1.13.2, LATEST viaversion (2.1.4 snapshop)

**Comment by Xernium** [comment] 2019-09-20 23:11
Confirm. This exists. Probably related to how the explosion mechanics changed in 1.14.4

**Comment by creeper123123321** [comment] 2019-10-13 15:54
Is this issue a duplicate of #1365?

**Comment by creeper123123321** [comment] 2019-11-13 22:09
Can you test if this bug still exists in the latest version from ci.viaversion.com?

**Closed** 2019-12-21 07:19 UTC
