### ISSUE TITLE
[1.20.1 -> 1.20.2] Regarding data packet errors caused by resource-pack

### ISSUE THREAD

**Issue by RICE0707** [ViaVersion/ViaVersion#3476] opened 2023-10-09 18:38 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/f6c382c2a790c6b22edbd50a02c851c6ed74724201362e7321b66b44e88227b0

### Console Error

```
com.mojang.authlib.GameProfile@6543caf1[id=4fad18b1-428d-4a38-a4cc-47919903afd2,name=RiceChen_,properties={textures=[Property[name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTY5Njg3NjM5OTg5MiwKICAicHJvZmlsZUlkIiA6ICI0ZmFkMThiMTQyOGQ0YTM4YTRjYzQ3OTE5OTAzYWZkMiIsCiAgInByb2ZpbGVOYW1lIiA6ICJSaWNlQ2hlbl8iLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQwZjViZDY4NTJmMzk3MDRhM2UzY2M4YzRjMmRmYWJkMmY3YmZhNzRlMjY1YTg1Mjc0YWFiMDk5MzM3MjYwNSIKICAgIH0KICB9Cn0=, signature=C8Lh2YSKSvbx7DegiSuEPAJvQ6BgRZwEnNOavGeBrreRYYIMDeImTvN80b3sTY8/l96z0556CWef+lKrPuFZcAGwQV3mHNfvkRb1YxuwjQkFSnRYGuZjDpZ9B0QY6PA/Q0OkSpb1cXLW7LkibGSLNtstsZFqO1dKDFh1/FmTZ3kREEywcjSO0nFglWNA052r6N2v6RnBmC2YgPZFPL7bb9uIsCCDvWcvroHK+dgaH9aYOCgVoI2dsfPCsCjhuhB7Ak3W2EFHak2geJmE9hFDNtAkaNCFxbrpV90Lon2XPATlofA/K5f/2x7UTMfC7jz1KOiwp0ijfzQXHc9I4J6Gaf1TrimTcvZUh3qgsucdn01Rd9suD9uTLNYn1EsDIBaXycLgRoVatACO+HNhCgMsjKbA83qLN9RFqV0AOUAsm78VeslAue1hteltcN3EEfzO5xrBbtIcMtjiSHPRY5hQOaJMWTKDahL11/Rf5CAQ3s34goc3OPueesBI/tIBRag8li+FDWS+bjXiMy+m16GfC9eAxydGM5BJM5ClzUHDt4PHv0zIKmxG7KqcFuarS++wuFkl2b3Njr4U9mMvi7OmljF6M27EmCS+casK7nEoH1bR2KTFua3fxqCepcvnsuOYjwLhhOdv5fkCKXqSwTGS3+EOu7jyM9Jc43cVePGIiUM=]]}] lost connection: Disconnected
```
![image](https://github.com/ViaVersion/ViaVersion/assets/68499464/701237cc-3a8f-4510-94f0-bd2e18157587)

### Bug Description

When I used the 1.20.1 client to log in to the purpur-1.20.2-2077 server, this exception occurred.

### Steps to Reproduce

When I use the 1.20.1 client to log in to the server of purpur-1.20.2-2077

### Expected Behavior

Log in normally

### Additional Server Info

Use ViaVersion-4.9.0-23w40a-SNAPSHOT.jar and ViaBackwards-4.9.0-23w40a-SNAPSHOT.jar

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2023-10-09 18:38
![Platform: git--Purpur--2077%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Purpur--2077%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w40a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w40a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w40a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w40a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by RICE0707** [comment] 2023-10-09 20:07
Replenish:
This error only occurs when I log in with a client version lower than the server version after setting the texture pack in resource-pack, regardless of whether the content of the texture pack is present or not, and the texture pack version

This is a texture pack with no content:
[air.zip](https://github.com/ViaVersion/ViaVersion/files/12850091/air.zip)

**Comment by kennytv** [comment] 2023-10-11 06:16
Are you using Bungee?

**Comment by RICE0707** [comment] 2023-10-11 14:33
> Are you using Bungee?

I don't use Bungee, but even if I do, I still get this error

**Comment by kennytv** [comment] 2023-10-11 14:36
Can't reproduce, try with a Paper server please

**Comment by RICE0707** [comment] 2023-10-11 15:18
After using paper, I still have this error:
https://cdn.discordapp.com/attachments/596718421966716928/1161684328330297364/2.gif?ex=653931d6&is=6526bcd6&hm=7c99a09be11f0f6850d9a0e55a76c9149d38c01abfa5a9f5f111cd52981e37df&
(The video file is too large and can only be sent using a link)

**Comment by kennytv** [comment] 2023-10-11 15:54
Please also try using a vanilla client

**Comment by RICE0707** [comment] 2023-10-11 15:55
> Please also try using a vanilla client

![image](https://github.com/ViaVersion/ViaVersion/assets/68499464/7718b542-1e3b-42a2-83bf-6c639ae35f88)
Still have this error

**Comment by RICE0707** [comment] 2023-10-11 16:01
> Please also try using a vanilla client, and the server should be running Via dev builds

In the latest development version, this error still exists
![image](https://github.com/ViaVersion/ViaVersion/assets/68499464/5d57d0e1-f30c-4195-86ba-bee520f34366)
![image](https://github.com/ViaVersion/ViaVersion/assets/68499464/26208721-8bef-4975-85fe-285e35a1ecd4)

**Comment by Barvalg** [comment] 2023-10-11 16:15
![Platform: git--Paper--233%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--233%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment] 2023-10-11 22:24
Ran a test for this issue and then it seems to vary, Some server RPs work fine and others will break viaversion. *(although assuming it breaks because of poor designs)*

**Comment by kennytv** [comment] 2023-10-15 08:13
Fixed in latest ViaBackwards dev build (once it finished building)

**Closed** 2023-10-15 08:12 UTC
Labels: Bug
