### ISSUE TITLE
ERROR IN Protocol1_8TO1_9 IN REMAP OF 0x15->0x04

### ISSUE THREAD

**Issue by bobhenl** [ViaVersion/ViaVersion#2336] opened 2021-02-10 23:37 UTC
**Describe the bug, provide any errors**
Hi, I got this error in console, prob when player joined/changed world/respawned, cause items from itemjoin were given to him.
https://pastebin.com/Gi1Jrfdv

**How can we reproduce it?**
1. Don't know sorry, all I know is that he respawned/joined/changed world.
2. Then the error occured https://pastebin.com/Gi1Jrfdv

**Expected behaviour**
Any error

**ViaVersion Dump**
https://dump.viaversion.com/a196abefa387beb0bd5545db807c2083d687b113a41bed2f056503775f384f5b

**Additional server info**
Yes I use Bungee, Yatopia and plugins:
[00:36:32 INFO]:  Plugins (53): AttrbQuickFix, AuthMe, BannerBoard, BowHub, ChatControlRed, ChatEmojis, Chunkmaster, Citizens, ClicksPerSecond, ConsoleSpamFix, CraftingStore, DeluxeAnnounce, DiscoFloor, FancyCropTrample, FastLogin, FeatherBoard, GadgetsMenu, HideItem, HolographicDisplays, HubPvPSword, HyperDrive, InfiniteJump, ItemJoin, JukeBox, JumpAndRuns, JumpPads, LiteBans, LuckPerms, MVdWPlaceholderAPI, Multiverse-Core, NametagEdit, NoCheatPlus, NoteBlockAPI, PlaceholderAPI, Plan, PocketGames, ProtocolLib, SecuredNetwork, ServerUtils, SkinsRestorer, SuperLobby, Trampolin, Vault, ViaBackwards, ViaBoundingBox, ViaRewind, ViaVersion, ViewDistanceTweaks, VoidGenerator, WorldEdit, WorldGuard, pHD and spark

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists – will update, this occurred for the first time, so wanna know  what¨s your opinion on it.
![image](https://user-images.githubusercontent.com/18662086/107587033-5b739280-6c01-11eb-9c05-c4ca9cf9f23a.png)

**Comment by KennyTV** [comment] 2021-02-10 23:41
Duplicate of https://github.com/ViaVersion/ViaRewind/issues/226

**Closed by KennyTV** 2021-02-10 23:41 UTC
