### ISSUE TITLE
Plugin wouldn't work on 1.20.2 server

### ISSUE THREAD

**Issue by Tsaitou7361** [ViaVersion/ViaVersion#3483] opened 2023-10-15 07:21 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/2ad70b7a125d52ac11704e669a4cb989cc2595b8d8d9022b3dce368552d9d6d6

### Console Error

```
[07:01:11] [User Authenticator #6/INFO]: UUID of player Tsaitou is be42e3fb-9623-3df5-9db8-a76432545711
[07:01:11] [Server thread/INFO]: com.mojang.authlib.GameProfile@5fd0a854[id=be42e3fb-9623-3df5-9db8-a76432545711,name=Tsaitou,properties={}] lost connection: Disconnected
```

### Bug Description

when I use 1.20.1 to connect 1.20.2 server (spigot, installed ViaVersion and ViaBackwards), it shows

```
Internal Exception io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index 64 out of bounds for length
```

### Steps to Reproduce

1. Login with 1.20.1 client
2. join a 1.20.1 spigot server
3. and boom!

### Expected Behavior

```
Internal Exception io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index 64 out of bounds for length
```

### Additional Server Info

I just use spigot
and following plugins
1. [Chunky](https://modrinth.com/plugin/chunky)
2. [ClickVillagers](https://modrinth.com/plugin/clickvillagers)
3. [DiscordSRV](https://modrinth.com/plugin/discordsrv)
4. [NoChatReports](https://www.spigotmc.org/resources/no-chat-reports.102990/)
5. [PlugManX](https://www.spigotmc.org/resources/plugmanx.88135/)
6. [TabTPS](https://modrinth.com/plugin/tabtps)
7. [ViaBackwards](https://modrinth.com/plugin/viabackwards)
8. [ViaVersion](https://modrinth.com/plugin/viaversion)
9. [Simple Voice Chat](https://modrinth.com/plugin/simple-voice-chat)

I also installed InteractiveChat and InteractiveChatDiscordSrvAddon, but it doesn't work :(

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2023-10-15 07:21
![Platform: 3909--Spigot--e0e223f--ad0e574%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-3909--Spigot--e0e223f--ad0e574%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Tsaitou7361** [comment] 2023-10-15 07:22
I have tried latest build that version number is 4.8.1

**Comment by kennytv** [comment] 2023-10-15 07:23
Try using -dev builds, otherwise most likely a duplicate of https://github.com/ViaVersion/ViaVersion/issues/3476

**Comment by Tsaitou7361** [comment] 2023-10-15 07:23
thanks, I will give it a try.

**Closed by kennytv** 2023-10-15 07:23 UTC
Labels: Unconfirmed

**Comment by Tsaitou7361** [comment] 2023-10-15 07:30
umm... It crashed

**Comment by Tsaitou7361** [comment] 2023-10-15 07:31
This is latest.log
```
[07:29:11] [ServerMain/WARN]: File not found or not readable: /proc/stat
[07:29:12] [ServerMain/WARN]: Failed to get system info for Microarchitecture
java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "this.cpuVendor" is null
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.queryMicroarchitecture(CentralProcessor.java:825) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.getMicroarchitecture(CentralProcessor.java:816) ~[oshi-core-6.4.5.jar:6.4.5]
	at net.minecraft.SystemReport.a(SourceFile:66) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at net.minecraft.SystemReport.a(SourceFile:128) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at net.minecraft.SystemReport.c(SourceFile:75) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at net.minecraft.SystemReport.a(SourceFile:82) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at net.minecraft.SystemReport.a(SourceFile:75) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at net.minecraft.SystemReport.c(SourceFile:52) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at net.minecraft.SystemReport.a(SourceFile:82) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at net.minecraft.SystemReport.<init>(SourceFile:52) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at net.minecraft.CrashReport.<init>(CrashReport.java:32) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at net.minecraft.CrashReport.h(CrashReport.java:250) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at net.minecraft.server.Main.main(Main.java:119) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at org.bukkit.craftbukkit.Main.main(Main.java:225) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at org.bukkit.craftbukkit.bootstrap.Main.lambda$1(Main.java:60) ~[spigot-1.20.2.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[07:29:19] [ServerMain/WARN]: You specified a resource pack without providing a sha1 hash. Pack will be updated on the client only if you change the name of the pack.
[07:29:20] [ServerMain/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[07:29:20] [ServerMain/ERROR]: Failed to start the minecraft server
net.minecraft.util.SessionLock$ExceptionWorldConflict: /Innovation/./world/session.lock: already locked (possibly by other Minecraft instance?)
	at net.minecraft.util.SessionLock$ExceptionWorldConflict.a(SourceFile:95) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at net.minecraft.util.SessionLock.a(SourceFile:41) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at net.minecraft.world.level.storage.Convertable$ConversionSession.<init>(Convertable.java:543) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at net.minecraft.world.level.storage.Convertable.validateAndCreateAccess(Convertable.java:456) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at net.minecraft.server.Main.main(Main.java:171) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at org.bukkit.craftbukkit.Main.main(Main.java:225) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3909-Spigot-e0e223f-ad0e574]
	at org.bukkit.craftbukkit.bootstrap.Main.lambda$1(Main.java:60) ~[spigot-1.20.2.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
