### ISSUE TITLE
Players kicked from 1.21.1 to 1.21.3 server when opening the blacksmith table with a network protocol error

### ISSUE THREAD

**Issue by shiksyt** [ViaVersion/ViaVersion#4244] opened 2024-11-05 18:09 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/a443bf66c3b08a44975f673aeafb55a0d5ad233649f2e70276e4e73b214097aa

### Console Error

```
Put the mclo.gs link or text here.
```
https://mclo.gs/H2pk1ap

### Bug Description

Players kicked from 1.21.1 to 1.21.3 server when opening the blacksmith table with a network protocol error

### Steps to Reproduce

1. Make a server on 1.21.3 Paper
2. Log in to it with 1.21.1
3. Open the blacksmith's table

### Expected Behavior

The blacksmith's table should open without crashing.

### Additional Server Info

I use Velocity, my plugins are in the logs above

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by shiksyt** [comment] 2024-11-05 18:16
https://dump.viaversion.com/523694cd54c4bb81cf66b9caa5e8c4ae366725e5f3814462a379b0514761b8a7
Nothing has changed

**Comment by kennytv** [comment] 2024-11-05 18:17
Duplicate of https://github.com/ViaVersion/ViaBackwards/issues/909

**Closed by kennytv** 2024-11-05 18:17 UTC
Labels: Unconfirmed
