### ISSUE TITLE
Kicked when login with 1.17 MC on 1.13 spigot because of IOException Expected root tag to be a CompoundTag

### ISSUE THREAD

**Issue by Elikill58** [ViaVersion/ViaVersion#2704] opened 2021-10-05 21:59 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/145bb496248de627bb52939a18837d306d52618f9f3e94afa1040e8da4c7ae54

### Console Error

```
[ViaVersion] ERROR IN Protocol1_13_1To1_13 IN REMAP OF DECLARE_RECIPES (0x54)
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: FlatVarIntItem Array, Data: [Pair{Type|VarInt, 524}, Pair{Type|String, minecraft:piston}, Pair{Type|String, crafting_shaped}, Pair{Type|VarInt, 3}, Pair{Type|VarInt, 3}, Pair{Type|String, }, Pair{Type|FlatVarIntItem Array, [Lcom.viaversion.viaversion.api.minecraft.item.Item;@3b96ec74}], Source 0: com.viaversion.viaversion.protocols.protocol1_13_1to1_13.packets.InventoryPackets$2 (Anonymous), Packet ID: 84}
Actual Error: 
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
	at net.minecraft.server.v1_13_R1.NetworkManager.lambda$4(NetworkManager.java:199)
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: FlatVarIntItem Array, Data: [Pair{Type|VarInt, 524}, Pair{Type|String, minecraft:piston}, Pair{Type|String, crafting_shaped}, Pair{Type|VarInt, 3}, Pair{Type|VarInt, 3}, Pair{Type|String, }, Pair{Type|FlatVarIntItem Array, [Lcom.viaversion.viaversion.api.minecraft.item.Item;@3b96ec74}], Source 0: com.viaversion.viaversion.protocols.protocol1_13_1to1_13.packets.InventoryPackets$2 (Anonymous), Packet ID: 84}
Actual Error: 
Caused by: java.io.IOException: Expected root tag to be a CompoundTag, was 6
	at com.viaversion.viaversion.libs.opennbt.NBTIO.readTag(NBTIO.java:181)
	at com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:52)
	at com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:36)
	at com.viaversion.viaversion.api.type.types.minecraft.FlatVarIntItemType.read(FlatVarIntItemType.java:43)
	at com.viaversion.viaversion.api.type.types.minecraft.FlatVarIntItemType.read(FlatVarIntItemType.java:29)
	at com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:49)
	at com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:30)
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:125)
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:171)
	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.data.RecipeRewriter1_13_2.handleCraftingShaped(RecipeRewriter1_13_2.java:56)
	at com.viaversion.viaversion.rewriter.RecipeRewriter.handle(RecipeRewriter.java:43)
	at com.viaversion.viaversion.protocols.protocol1_13_1to1_13.packets.InventoryPackets$2.lambda$registerMap$0(InventoryPackets.java:90)
	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290)
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269)
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528)
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70)
	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
	at net.minecraft.server.v1_13_R1.NetworkManager.lambda$4(NetworkManager.java:199)
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: FlatVarIntItem Array, Data: [Pair{Type|VarInt, 524}, Pair{Type|String, minecraft:piston}, Pair{Type|String, crafting_shaped}, Pair{Type|VarInt, 3}, Pair{Type|VarInt, 3}, Pair{Type|String, }, Pair{Type|FlatVarIntItem Array, [Lcom.viaversion.viaversion.api.minecraft.item.Item;@3b96ec74}], Source 0: com.viaversion.viaversion.protocols.protocol1_13_1to1_13.packets.InventoryPackets$2 (Anonymous), Packet ID: 84}
Actual Error: 
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
	at net.minecraft.server.v1_13_R1.NetworkManager.lambda$4(NetworkManager.java:199)
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: FlatVarIntItem Array, Data: [Pair{Type|VarInt, 524}, Pair{Type|String, minecraft:piston}, Pair{Type|String, crafting_shaped}, Pair{Type|VarInt, 3}, Pair{Type|VarInt, 3}, Pair{Type|String, }, Pair{Type|FlatVarIntItem Array, [Lcom.viaversion.viaversion.api.minecraft.item.Item;@3b96ec74}], Source 0: com.viaversion.viaversion.protocols.protocol1_13_1to1_13.packets.InventoryPackets$2 (Anonymous), Packet ID: 84}
Actual Error: 
Caused by: java.io.IOException: Expected root tag to be a CompoundTag, was 6
	at com.viaversion.viaversion.libs.opennbt.NBTIO.readTag(NBTIO.java:181)
	at com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:52)
	at com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:36)
	at com.viaversion.viaversion.api.type.types.minecraft.FlatVarIntItemType.read(FlatVarIntItemType.java:43)
	at com.viaversion.viaversion.api.type.types.minecraft.FlatVarIntItemType.read(FlatVarIntItemType.java:29)
	at com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:49)
	at com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:30)
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:125)
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:171)
	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.data.RecipeRewriter1_13_2.handleCraftingShaped(RecipeRewriter1_13_2.java:56)
	at com.viaversion.viaversion.rewriter.RecipeRewriter.handle(RecipeRewriter.java:43)
	at com.viaversion.viaversion.protocols.protocol1_13_1to1_13.packets.InventoryPackets$2.lambda$registerMap$0(InventoryPackets.java:90)
	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290)
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269)
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528)
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70)
	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
	at net.minecraft.server.v1_13_R1.NetworkManager.lambda$4(NetworkManager.java:199)
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)
```

### Bug Description

Kick when try to login on 1.13 server from 1.17 client

### Steps to Reproduce

1. Launcher MC 1.17
2. Start MC server 1.13 (v_1_13_R1)
3. Try to login

### Expected Behavior

Can login

### Additional Server Info

I also have ProtocolLib 4.7.0 installed but even without it kick me

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment] 2021-10-06 07:31
Duplicate of https://github.com/ViaVersion/ViaVersion/issues/2383 - an easy fix is to just update to 1.13.2, since there should be no sane reason to stay on 1.13.0

**Closed by kennytv** 2021-10-06 07:31 UTC
Labels: Unconfirmed
