### ISSUE TITLE
Packet block connection leaves ghost blocks

### ISSUE THREAD

**Issue by andreasdc** [ViaVersion/ViaVersion#2456] opened 2021-04-29 16:36 UTC
### '/viaversion dump' Output

-

### Bug Description

When you explode tnt, very often there are ghost/client blocks left.

### Steps to Reproduce

1.16.5 client version.
1.8 serevr

### Expected Behavior

no client blocks, on world level there are no ghost blocks, but it uses more resources as I believe.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment] 2021-04-29 16:40
Duplicate of https://github.com/ViaVersion/ViaVersion/issues/2296

**Comment by andreasdc** [comment] 2021-04-29 16:41
@KennyTV really you still didn't fix this?

**Closed by KennyTV** 2021-04-29 16:40 UTC
