### ISSUE TITLE
Double Playing Sounds [Clicking stone buttons, Picking up Items, Exiting GUI's / Inventories]

### ISSUE THREAD

**Issue by VideoklipBG** [ViaVersion/ViaVersion#773] opened 2017-11-11 10:08 UTC
### What is the output link of /viaversion dump? 

[https://gist.github.com/4c0d218e56e48b7ddac4f9299f3b86ff](https://gist.github.com/4c0d218e56e48b7ddac4f9299f3b86ff)

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

[Waterfall](https://aquifermc.org/threads/welcome-to-waterfall.1/) (Fork / Optimized Version of BungeeCord)

`Waterfall version git:Waterfall-Bootstrap:1.12-SNAPSHOT:261741a:155 by md_5`

Other Plugins: _N/A_

### How does this error happen? login? Using an item? 

Some sounds are double played for clients - MC Version 1.9+ (On 1.8.8 Spigot Servers using BungeeCord (Waterfall) and ViaVersion)

Tested with: [BungeeCord](https://www.spigotmc.org/wiki/bungeecord/) (Official) & [Waterfall](https://aquifermc.org/threads/welcome-to-waterfall.1/) (Fork of BungeeCord)

Affects: MC Clients 1.9, 1.9.2, 1.9.4, 1.10, 1.10.1, 1.10.2, 1.11, 1.11.1, 1.11.2, 1.12, 1.12.1, 1.12.2

Issue occurs when:

- Clicking Stone Button;
- Picking up Item; Firing Dispensers / Droppers;
- Using Bow / Fishing Rod;
- Exiting GUI's / Inventories (Example: Furnace / Chest) while sounds are playing (Breaking Blocks, Minecarts, Ambient Sounds, etc.)

### Is there an error in the console? Use pastebin.com. Is there a kick message?

_N/A_

**Comment by Matocolotoe** [comment] 2019-04-23 16:50
it's a bug in vanilla minecraft i think

**Comment by MylesIsCool** [comment] 2019-05-11 18:03
I'm going to close this because it's not consistently reproducible (I haven't experienced it). If there's some specific situation where it happens 100% and doesn't happen in vanilla (please provide steps), we'll reopen :)

**Closed by MylesIsCool** 2019-05-11 18:03 UTC
Labels: Won't Fix
