### ISSUE TITLE
ERROR IN Protocol1_8TO1_9 IN REMAP OF 0x15->0x04

### ISSUE THREAD

**Issue by Malachiel87** [ViaVersion/ViaVersion#2345] opened 2021-02-13 23:22 UTC
**Describe the bug, provide any errors**
https://ghostbin.co/paste/26e6w

**How can we reproduce it?**
Join with 1.8 client on my creative server 1.16.54

**Expected behaviour**
no crash

**ViaVersion Dump**
https://dump.viaversion.com/6ea0bd1127c211c87e92b146da3bc0218807ce24d9bd73201815974a6153b020

**Additional server info**
Paper

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment] 2021-02-13 23:26
Duplicate of https://github.com/ViaVersion/ViaRewind/issues/226

**Closed by KennyTV** 2021-02-13 23:26 UTC
