### ISSUE TITLE
InventoryClickEvent dup bug

### ISSUE THREAD

**Issue by LaivyTLife** [ViaVersion/ViaVersion#2794] opened 2022-01-08 11:31 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/1950e8d9ebf40234b0b01c463ddb6fddc0e3289fa53106f4031c0f76cfed3e60

### Console Error

```
Nothing
```

### Bug Description

Login into an 1.18.1 server at 1.12.x (not tested in another versions) and try to use guis, if you click two times, you can dup the item.

I think that is a problem with the `event.setCancelled(true)` of the `InventoryClickEvent` from bukkit.

I tested at the 1.18.1 client version, the bug didnt appears.

### Steps to Reproduce

1. Log-in with a 1.12 client into a 1.18.1 minecraft server (using ViaBackwards)
2. Try to use the menus, click two times in the same item (the menu needs to be the click action cancelled)
3. Tadaaa, the bug.

### Expected Behavior

The event's correct cancel

### Additional Server Info

ViaBackwards 4.1.2-SNAPSHOT, Paperspigot 1.18.1 build 134, ProtocolLib 4.8.0-SNAPSHOT-b540, Vault 1.7.3-b131, ViaVersion 4.1.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2022-01-08 11:31
![Platform: git--Paper--134%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Paper--134%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 9 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment] 2022-01-08 11:32
Not a dupe; duplicate of https://github.com/ViaVersion/ViaBackwards/issues/389

**Closed by kennytv** 2022-01-08 11:32 UTC
Labels: Unconfirmed
