### ISSUE TITLE
skull_item to chat hover message error

### ISSUE THREAD

**Issue by P-JungMin** [ViaVersion/ViaVersion#2277] opened 2021-01-06 13:32 UTC
####I am not good at English. So I wrote this with Google Translator. If you can't understand what I'm saying, let me know.####

**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

**How can we reproduce it?**
1. Login on 1.12
2. Login on 1.16.4 using another client
3. hold custom designed(display name and image changed with hdb) in hand then chat 'blabla [i] blabla' (my plugin will change [i] to an item hover message.)
4. all of 1.16 client encounters an error and the connection is closed (error stacktrace: https://pastebin.com/1N52vxhM)

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/46414840/103772913-9c5e1180-506d-11eb-8b55-b0f9f7f76c7b.png)
![image](https://user-images.githubusercontent.com/46414840/103773083-db8c6280-506d-11eb-8b91-17505f965bcb.png)
![image](https://user-images.githubusercontent.com/46414840/103773184-02e32f80-506e-11eb-9c97-1c99b142f5c3.png)

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/cad855cd464c742a439229aead129b636f28ca545e87202a60803930a5b24411
**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
using paper and my plugin
and in plugin, i used this code (https://pastebin.com/dPwwu8gt) to change item to hover event component

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment] 2021-01-06 13:35
Duplicate of https://github.com/ViaVersion/ViaBackwards/issues/270

**Closed by KennyTV** 2021-01-06 13:35 UTC
