### ISSUE TITLE
SuperiorSkyblock - Falling into blocks 

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#1438] opened 2019-09-06 14:50 UTC
**Describe the bug, provide any errors**
On my SuperiorSkyblock server, whenever you stand around not doing much, you randomly glitch into the island and cant move

**How can we reproduce it?**
1. Login on 1.14.4 MC client'
2. Make sure the server version is paperspigot 1.13.2.'
3. Jump around a skyblock island and dont move for a bit

**Expected behaviour**
You will glitch into the island

**Screenshots**

**ViaVersion Dump:**
- https://dump.viaversion.com/70da063e40f5ce5c61be1f9f20e02bc88ee4045e944654226ce0b9ab02aff892

**Additional server info**
Bungeecord and superiorskyblock plugin

**Comment by MylesIsCool** [comment] 2019-09-09 06:40
Have you tested the latest build of ViaVersion? We did change some stuff with explosions which if the plugin uses it, it may fix. Otherwise you're gonna need to contact the plugin author as it's a paid plugin which we don't own, I'd suspect it might be down to how they're setting the blocks. It might be a packet method which confuses ViaVersion.

**Comment by OmerBenGera** [comment] 2019-09-13 08:09
I am the author of the skyblock plugin.
I set blocks using the following method:
(1.14) chunk.setType(blockPosition, Block.getByCombinedId(combinedId), true);
(1.13) chunk.a(blockPosition, Block.getByCombinedId(combinedId), true);

**Comment by MylesIsCool** [comment] 2019-09-13 08:16
@OmerBenGera Do you do this async? Or do anything special in regards to how you're calling this?

Also why not use the Bukkit API?

**Comment by OmerBenGera** [comment] 2019-09-13 08:32
@MylesIsCool I am not doing this async, or anything special.
I don't use the Bukkit API as this method is much more performance friendly, and for large amount of block updates - the API method is not the way to go.

**Comment by MylesIsCool** [comment] 2019-09-13 08:48
@OmerBenGera are you able to replicate the bug yourself?

**Comment by OmerBenGera** [comment] 2019-09-13 08:54
@MylesIsCool Haven't tried, but he wasn't the only one to be able to replicate it.
I am willing to give you a copy in order to get this thing sorted out.

**Comment by MylesIsCool** [comment] 2019-09-13 17:14
@OmerBenGera I don't currently have the time to investigate this one, as it's one of those issues which will probably take a few hours to solve. If possible I'd suggest ensuring you can replicate it yourself in the case it might be a bad Bungee rewrite or something weird like that. Otherwise, if you want to message me on Spigot I'll try to take a look over the next few weeks or so.

**Comment by JHarris12345** [comment] 2019-09-14 14:14
Damn a few weeks, this issue is SO annoying and I am certain connected to VV. To replicate it, just stand on a skyblock and do nothing for a while, you will glitch in. Or just play skyblock normally for 10 - 15 minutes and watch it happen

**Comment by MylesIsCool** [comment] 2019-09-16 12:05
You're more than welcome to continue further investigation to narrow down the problem. It would be worth ensuring you have no other plugins when testing.

Something strange is definitely going on considering that this issue has only been reported with SuperiorSkyblock.

I have a full-time job so ViaVersion is a hobby at the end of the day but you are more than welcome to uninstall it if it's causing you issues.

**Comment by JHarris12345** [comment] 2019-09-16 14:45
@MylesIsCool So if I uninstall, is there another plugin I can use to allow both 1.14 and 1.8 players to connect to my 1.13.2 server?

**Comment by MylesIsCool** [comment] 2019-09-16 14:56
> @MylesIsCool So if I uninstall, is there another plugin I can use to allow both 1.14 and 1.8 players to connect to my 1.13.2 server?

ProtocolSupport is the only alternative which only works on latest server (1.14)

**Comment by JHarris12345** [comment] 2019-09-16 17:03
@MylesIsCool You know I cant use protocolsupport because my server is 1.13 and I need 1.14 players to join. My only option is viaversion

**Comment by JHarris12345** [comment] 2019-09-16 17:31
Ive tested it with no plugins and just viaversion. It happens, please just look over the code, Omer gave you his info etc. Its a VV glitch that really needs solving, its breaking my server and ProtocolSupport is no option

**Comment by JHarris12345** [comment] 2019-09-16 17:35
I enabled VV debug and this was the output at the time player JHarris12345 was glitching https://pastebin.com/jhKmWhAD

**Comment by JHarris12345** [comment] 2019-09-16 21:12
Ok @MylesIsCool and @OmerBenGera. I successfully located the cause of the glitch so if you would forget everything that was said previously and just read this comment, I think you both need to work out which plugin needs fixing:

The island glitch of falling into blocks is caused on the 1.13.2 server when a 1.14 player creates an island. All other 1.14 players will glitch at this point. If you are on 1.13 or lower, you will not be affected by the glitch and will not cause it. It is ONLY for 1.14 client players.

When the server is on straight 1.14 and we don't have ViaVersion installed (so everyone joins in 1.14), the glitch does NOT happen. It only happens when the server is on 1.13 and we use ViaVersion. So this makes me think it is linked to ViaVersion.

Either way, the glitch is very annoying so please, now we have located the source of the glitch and can replicate it every single time. Can we produce a fix

**Comment by OmerBenGera** [comment] 2019-09-17 15:19
@MylesIsCool after some testings, we found out it also happens when SuperiorSkyblock places schematics using FAWE (their paste method for schematics).

**Comment by Xernium** [comment] 2019-09-23 15:31
FAWE is unsafe to use. It will generate these issues even when nothing else is being used. The server block state is inconsistent if that happens. I don't think that's something ViaVersion can do anything about. If this still happens if the plugin uses the normal WorldEdit I think we can label this a VV issue

**Comment by MylesIsCool** [comment] 2019-09-23 17:49
Pretty much what @Xernium said, having the option to swap to WE would probably be a great idea.

**Comment by OmerBenGera** [comment] 2019-09-23 18:27
@Xernium @MylesIsCool but that's not FAWE, as it also happens also without FAWE installed, and only SuperiorSkyblock. It probably happens because that's an empty world, and not vanilla one (for skyblock obviously). That's 100% ViaVersion. Please take a look at that.

**Comment by Xernium** [comment] 2019-09-23 18:33
@Xernium Empty worlds are a vanilla feature. I think what the skyblock plugin is doing is very sketchy. Ill take a look *when I have the time*

**Comment by OmerBenGera** [comment] 2019-09-23 18:36
Sketchy? Pasting blocks using an NMS method or creating an empty world?
You're just blaming other plugins (SuperiorSkyblock, FAWE...) instead of checking it.
The issue was reported almost 3 weeks ago, and nothing changed.

**Comment by Xernium** [comment] 2019-09-23 18:41
@OmerBenGera Since you ARE the author of the plugin; What method do you use for pasting the islands? Do you use packets to update? I am trying to understand how your plugin interacts with the NMS to see how this impacts the connection

**Comment by OmerBenGera** [comment] 2019-09-23 18:43
@Xernium as I said earlier:
> I set blocks using the following method (nms):
(1.14) chunk.setType(blockPosition, Block.getByCombinedId(combinedId), true);
(1.13) chunk.a(blockPosition, Block.getByCombinedId(combinedId), true);

**Comment by Xernium** [comment] 2019-09-23 18:44
@OmerBenGera I am more interested in how you run that. Is that scheduled or is that a part of the main thread? Is it possibly async?

**Comment by OmerBenGera** [comment] 2019-09-23 18:45
@Xernium Fully synced (on main thread)

**Comment by Xernium** [comment] 2019-09-23 19:03
@OmerBenGera are you passing the NBT to TileEntities or does this happen with all blocks?

**Comment by Xernium** [comment] 2019-09-23 19:11
I have observed something odd while at this- It seems that Via sends packets directly for this to be consistent. When the block is updated again this *might* cause issues. I am not sure how and why though.

**Comment by Xernium** [comment] 2019-09-23 19:16
However I have now observed ProtocolSupport also doing this. I need to compare data in a bit. Something is off

**Comment by MylesIsCool** [comment] 2019-09-25 19:07
I'm probably gonna need further info after JHarris gave me the plugin, I've attempted to replicate the issue with the plugin as follows:
- 1.13.2 Paper Server
- Fast Async WorldEdit
- 2 1.14.4 Clients

I create islands and delete them but seem not to observe the issue, I've tried with and without FAWE. But also pasting schematics in the same place to see if there is an issue there and also cannot replicate. I'm trying to replicate this in a minimalistic environment if you're able to point to what I might be missing so I can replicate this it would be appreciated.

Essentially I don't observe this:

> The island glitch of falling into blocks is caused on the 1.13.2 server when a 1.14 player creates an island. All other 1.14 players will glitch at this point. If you are on 1.13 or lower, you will not be affected by the glitch and will not cause it. It is ONLY for 1.14 client players.

This is what my ViaVersion dump info looks like https://dump.viaversion.com/a854b07e4f33ac5a35a0b1d56f1c3c00beec6e34b857dc1d8cad4e5f6c1afd8f

Ideally gonna need to know what I need to do/change to replicate this so I can look at it further. Worth noting this is being debugged on localhost.

**Comment by JHarris12345** [comment] 2019-09-30 01:15
Create an island, start building a little bit. Just place a few blocks. Bring on an alt in 1.14.4 client too and have them create an island.

**Comment by MylesIsCool** [comment] 2019-09-30 17:10
@JHarris12345 This is pretty much what I did when I tried it, is there a chance you can show a video on a similar setup to what I used so I can be sure i'm doing it right?

**Comment by Alienbyte** [comment] 2020-01-03 01:00
I'm having this issue on 1.12 Paper, and could probably get a video of someone who gets glitched but would take a bit of effort lol.

Have confirmed the glitch is somehow client side? Players will go into the ground, but on my screen it shows them above the ground. And once they relog it fixes as well.

Really would love to help get this resolved. :)

**Comment by HowardZHY** [comment] 2024-04-25 17:13
This should be closed as outdated

**Closed** 2024-04-25 17:15 UTC
Labels: Can't Reproduce
