### ISSUE TITLE
1.20.4 users stuck in Loading terrain screen for 30s

### ISSUE THREAD

**Issue by clrxbl** [ViaVersion/ViaVersion#3695] opened 2024-02-14 16:19 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/dcf77d6029c5d983e436ac2a9ebd7c0636dec864c23f13c39fdd28051ed118fd

### Console Error

N/A

### Bug Description

With a 1.19.4 Paper server and ViaVersion on the Velocity proxy, clients get stuck on Loading terrain upon joining the server for 30 seconds.

### Steps to Reproduce

1. Login with a 1.20.4 client

### Expected Behavior

Not get stuck on a Loading terrain screen for 30 seconds.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2024-02-14 16:19
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--ef861819--b358%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--ef861819--b358%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w06a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w06a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment] 2024-02-14 17:31
Can reproduce this problem, but it seems to be fixed in paper 1.20.2.

**Comment by BingYanchi** [comment] 2024-02-18 15:46
This issue has been raised at https://github.com/ViaVersion/ViaVersion/issues/3630, but no one has ever fixed it.

**Comment by Kichura** [comment] 2024-02-18 15:46
Will mark this as duplicate then.

**Closed by Kichura** 2024-02-18 15:46 UTC
Labels: Bug
