### ISSUE TITLE
Unable to interact with villagers on 1.15-pre6

### ISSUE THREAD

**Issue by ishland** [ViaVersion/ViaVersion#1555] opened 2019-12-08 07:44 UTC
**Describe the bug, provide any errors**
As soon as I right click on a villager, it kicks me.
The same thing happens when I remove ProtocolSupport

**How can we reproduce it?**
1. Login on 1.15-pre6
2. Click on a villager
3. I got kicked with Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.

**Expected behaviour**
I should be able to trade with the villager.

**ViaVersion Dump:**
https://dump.viaversion.com/f11ffca15c7aafaaa75d9ff3e56d8caf83dc7587cbfcb31cc5ef61a03b5265b0

**Additional server info**
This server is running Paper version git-Paper-234 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by Gerrygames** [comment] 2019-12-09 11:06
I can't reproduce the issue. Could you set debug=true in server.properties and send us the full error?

**Comment by TheMasterBlaster** [comment] 2019-12-09 18:20
I can confirm that I also have this issue has the same result running ViaVersion on the Proxy "Waterfall" when connected to a 1.14.4 native server. Here is a link to what the console showed during this issue https://pastebin.com/09P7fh6V

**Comment by KennyTV** [comment] 2019-12-09 18:32
Should be fixed with #1562 - could you test with the latest dev build, just to be sure?

**Comment by TheMasterBlaster** [comment] 2019-12-09 18:42
All seems good on my end now

**Closed** 2019-12-09 18:43 UTC
