### ISSUE TITLE
ProtocolLib Spam

### ISSUE THREAD

**Issue by AlansS53** [ViaVersion/ViaVersion#1506] opened 2019-10-31 03:29 UTC
**Describe the bug, provide any errors**
I have some performance issues on my server, so I activated ProtocolLib debug to get more information.
After a few hours my server logs had a 3GB size of the same error: https://pastebin.com/rs0mGfZm
They told me it's a ViaVersion problem

**Expected behaviour**
Turn ProtocolLib debug

**ViaVersion Dump:**
https://dump.viaversion.com/054238ee05b045da0a9fe2c9ceeb9883084338e2ef4eade467512f3a06497355

**Additional server info**
My server is PaperSpigot 1.8.8 but this error also happens in Spigot

**Comment by creeper123123321** [comment] 2019-10-31 07:58
Performance problem seems to be caused by Exceptions

**Comment by creeper123123321** [comment] 2019-10-31 08:10
Related to #1490

**Comment by FormallyMyles** [comment] 2020-06-06 11:11
I believe ProtocolLib now excludes this exception so gonna close this. Otherwise, enabling debug=true in server.properties can yield better results sometimes.

**Closed by FormallyMyles** 2020-06-06 11:11 UTC
