### ISSUE TITLE
Decoder exception (ViaFabric & ViaBackwards on client)

### ISSUE THREAD

**Issue by IkeVoodoo** [ViaVersion/ViaVersion#2987] opened 2022-06-28 21:29 UTC
### `/viaversion dump` Output

I do not have access to /viaversion dump on the client

### Console Error

![image](https://user-images.githubusercontent.com/55694349/176299015-b250f398-7550-43f3-bfae-63549495175b.png)

Using ViaFabric

### Bug Description

Joining games in PVPLegacy seems to cause you to get disconnected

### Steps to Reproduce

1. Login with ViaFabric and ViaBackwards on play.pvplegacy.net
2. Queue for a match or spectate one
3. Get kicked

### Expected Behavior

You should be getting teleported into the game

### Additional Server Info

I do not know what PVPLegacy uses

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2022-06-28 21:29
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by IkeVoodoo** [comment] 2022-06-28 21:30
Tasks where completed to post, I was unable to actually provide anything requested in them

**Comment by creeper123123321** [comment] 2022-06-29 09:50
> I do not have access to /viaversion dump on the client

Join singleplayer and run that command. Also please add the game log

**Comment by creeper123123321** [comment] 2022-06-29 11:58
duplicate of https://github.com/ViaVersion/ViaFabric/issues/182

**Closed by creeper123123321** 2022-06-29 11:58 UTC
Labels: Unconfirmed
