### ISSUE TITLE
Issue with Armor Stands on legacy versions

### ISSUE THREAD

**Issue by Firosee** [ViaVersion/ViaVersion#2984] opened 2022-06-27 19:29 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/6b5b082052459c93cdea04331c691afc8916049fffc9a1f8476ff7cd025c603c

### Console Error

None

### Bug Description

Armor stands via a plugin look weird on 1.8 compared to 1.16..

Video from 1.8: https://gyazo.com/6aaae012c17f7def0216dfd5741a92e9 (you can see the pickaxe is more in the arm than anything)

Video from 1.16: https://gyazo.com/ace7735cd00f1b7b6d57a77fd0bed0d2 (you can see the pickaxe works as intended in the hand)

### Steps to Reproduce

None

### Expected Behavior

The armor stand should be working the same but it looks more as if its on the arm rather than the hand on 1.8. You can see the armor stand arm moves but the pickaxe doesnt.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by FormallyMyles** [comment] 2022-06-30 21:32
Duplicate of https://github.com/ViaVersion/ViaVersion/issues/2055

**Closed by FormallyMyles** 2022-06-30 21:32 UTC
Labels: Unconfirmed
