### ISSUE TITLE
Opening gate disconnects connected fence blocks

### ISSUE THREAD

**Issue by Bobcat00** [ViaVersion/ViaVersion#1297] opened 2019-04-26 11:38 UTC
Running 1.14 client on CraftBukkit 1.12.2 server with ViaVersion SNAPSHOT build 326.  I have a fenced-in area with a gate.  Opening the gate causes all the fence blocks to be disconnected.  The same thing happens when closing the gate (i.e., they were connected before closing).  Also affects cobblestone walls when wall blocks are moved via pistons.
 
Before:
![2019-04-26_07 25 00](https://user-images.githubusercontent.com/3617206/56804935-69221300-67f5-11e9-9d78-e9ce3cd24176.png)
 
After:
![2019-04-26_07 25 18](https://user-images.githubusercontent.com/3617206/56804939-6f17f400-67f5-11e9-8304-e2cce9fef62d.png)

**ViaVersion Dump:**
https://dump.viaversion.com/467a06ee20d10b580b50176a4ad0acf10041dadf98b4fe7ba9c2b3cee16f9e97

**Additional server info**
Standalone server.  No Bungeecord.
serverside-blockconnections: true
blockconnection-method: world
reduce-blockstorage-memory: true
flowerstem-when-block-above: false

**Comment by Bobcat00** [comment] 2019-04-27 19:31
This is still a problem in build 329.

**Comment by Bobcat00** [comment] 2019-04-28 18:47
If I set **reduce-blockstorage-memory: false**, then fences are rendered properly when I open/close the gate, but the cobble walls are still wrong.

**Comment by creeper123123321** [comment] 2019-04-29 20:29
Maybe it is caused by a missing block tag https://minecraft.gamepedia.com/Java_Edition_1.14#Command_format

**Comment by creeper123123321** [comment] 2019-05-01 21:13
Should be fixed in latest build

**Comment by MylesIsCool** [comment] 2019-05-01 21:16
^^ thanks creeper :)

**Closed by MylesIsCool** 2019-05-01 21:16 UTC
Labels: Bug

**Comment by Bobcat00** [comment] 2019-05-01 22:01
Looks much better.  Tested with 1.12.2 server and 1.14 client.  Thanks!
