### ISSUE TITLE
GUI bug in 1.8.9

### ISSUE THREAD

**Issue by jakkeren** [ViaVersion/ViaVersion#2306] opened 2021-01-29 21:34 UTC
Basically, formatted inventories created with a 1.16 jar, won't display any color codes at all in 1.8.9. I'm using skript to create some of my GUI's, but I don't suppose it's a problem with skript, since I've seen this issue documented on other forums.

**Steps to reproduce the behavior:**
1. From a server with version **1.16.x**, use any skript to create a GUI with a colored name
2. Change your minecraft version to 1.8.9 and join with ViaRewind + ViaVerson + ViaBackwards
3. From version 1.8.9, the name of the GUI is now displayed without any color or formatting at all

**Expected behaviour**
I expected the inventories to be shown formatted in version 1.8.9, as they are in 1.16.x.

**Screenshots**
![Screen Shot 2021-01-29 at 22](https://user-images.githubusercontent.com/77197010/106328993-00e14a80-6281-11eb-842c-40146035866f.png)

**ViaVersion Dump**
https://dump.viaversion.com/e3f0f8f4669a9e52cf65dff8466e16bc79853e0f3064b69eca31ab85e63d4321

**Additional server info**
My server is running with bungeecord. A full list of our plugins can be seen here:
![Screen Shot 2021-01-29 at 22 27 47](https://user-images.githubusercontent.com/77197010/106329174-4d2c8a80-6281-11eb-856f-a804b2cd579e.png)

**Checklist**
- [yes] I have included a Viaversion dump
- [yes] If applicable, I have included a paste (not a screenshot) of the error
- [yes] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment] 2021-01-29 21:35
Duplicate of https://github.com/ViaVersion/ViaBackwards/issues/269

**Closed by KennyTV** 2021-01-29 21:35 UTC
