### ISSUE TITLE
Protocol 1_13 to 1_12_2 Error

### ISSUE THREAD

**Issue by FaiqGaming** [ViaVersion/ViaVersion#1869] opened 2020-07-01 08:56 UTC
Hello, why i got this error into my server?
```
[08:54:55 INFO]: Theindo448 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: Chunk, Source #1: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9$1 (Anonymous), Data: [], Packet ID: 34}
Actual Error:```
I don't know how to fix this error!

**Comment by KennyTV** [comment] 2020-07-01 08:56
Duplicate of #1860

**Closed by KennyTV** 2020-07-01 08:56 UTC
