### ISSUE TITLE
Respawning cause player to lost connection

### ISSUE THREAD

**Issue by DeonHarwnart** [ViaVersion/ViaVersion#2942] opened 2022-06-10 08:47 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/659f91ef3050ba5e4553957265477de205f424848f90042c1f40c6f76a4803fa

### Console Error

https://paste.gg/p/anonymous/a3b619df894143d1abccf322b5fbbe22

### Bug Description

Every time the player died and respawn, they got kicked out.

Message: An internal error occurred in your connection.

### Steps to Reproduce

1. Velocity and Paper Server
2. Die in the game and respawn

### Expected Behavior

The player should not get kicked out.

### Additional Server Info

Velocity and Paper

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2022-06-10 08:47
![Platform: velocity%203.1.1](https://img.shields.io/badge/Platform-velocity%203.1.1-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.0): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment] 2022-06-10 08:48
Duplicate of https://github.com/ViaVersion/ViaVersion/issues/2914

**Closed by kennytv** 2022-06-10 08:48 UTC
Labels: Unconfirmed
