### ISSUE TITLE
Cant connect using 1.8.9

### ISSUE THREAD

**Issue by Gilthunderx** [ViaVersion/ViaVersion#2752] opened 2021-12-03 01:57 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/ffd7d24c5e08f771bf116a31390f6ef9c55d7af64c9fd62d9825eccf97a1c1fd

### Console Error

```
Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viabackwards.protocol.protocol1_13_1to1_13_2.packets.EntityPackets1_13_2$3 (Anonymous)}```


### Bug Description

My players cant connect to my server using 1.8.9 version lunar client or laby mod.

### Steps to Reproduce

1, Login with 1.8.9 or 1.12 lunar client or laby mod.
2. Fails to connect to the server.

### Expected Behavior

Suppose to connect with no problems, this happened when I update to newer version

### Additional Server Info

_No response_

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2021-12-03 01:57
![Platform: git--Airplane--12%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Airplane--12%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.1--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.1.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment] 2021-12-03 07:55
Duplicate of https://github.com/ViaVersion/ViaBackwards/issues/412

**Closed by kennytv** 2021-12-03 07:55 UTC
Labels: Unconfirmed
