### ISSUE TITLE
Text display entities are broken when connecting to 1.19.4 server with a 1.20.1 client

### ISSUE THREAD

**Issue by avaruus1** [ViaVersion/ViaVersion#3379] opened 2023-07-09 14:46 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/d9451b579db44ee55da65cf19fc2b1337c7d5a3f931a5c9ce3ce20dcca70be5d

### Bug Description

Text display entities with any billboard type other than `fixed` are invisible to 1.20.1 clients on a 1.19.4 server. 

### Steps to Reproduce

Example:
1. Login with 1.20.1 client
2. Summon a text display entity: `/summon text_display ~ ~ ~ {billboard:"center",text:'{"text":"aaaaaaaaaaaaaaa"}'}`
3. The display entity is invisible

### Expected Behavior

The display entity should be visible.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2023-07-09 14:46
![Platform: 1.19.4--10.0.0--RC0](https://img.shields.io/badge/Platform-1.19.4--10.0.0--RC0-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Jo0001** [comment] 2023-07-16 18:02
Duplicate of #3383

**Closed by Jo0001** 2023-07-16 18:02 UTC
Labels: Duplicate
