### ISSUE TITLE
Loom is not working on not server version

### ISSUE THREAD

**Issue by TheSirCororo** [ViaVersion/ViaVersion#3304] opened 2023-04-24 14:41 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/b189295dfeda95e36d2a7f791c0b6fba3d9ea3b7db1f25f12dc19676172154bc

### Console Error

```
nope
```

### Bug Description

When I open Loom on 1.18.2 (server version) I can draw banner and it works good. When I open Loon on 1.19.3 (not server version) I can't draw banner because I put banner and dye and flag menu is not opened.

### Steps to Reproduce

1. Login with not server version
2. Open Loom
3. Put banner and dye
4. See that you can't draw banner

### Expected Behavior

I can draw banner

### Additional Server Info

Velocity 3.2.0-SNAPSHOT + Paper 1.18.2-387

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2023-04-24 14:41
![Platform: git--Paper--387%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--387%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.2): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment] 2023-04-24 14:45
Duplicate of #2938.

**Closed as not planned by Kichura** 2023-04-24 14:45 UTC
Labels: Duplicate

**Comment by TheSirCororo** [comment] 2023-04-24 14:52
Still not working. https://dump.viaversion.com/c60328687b80f3b55968522a17202771e49a401c4bb7361bc970cd9c6ae15908

**Comment by Barvalg** [comment] 2023-04-24 14:52
![Platform: git--Paper--387%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--387%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
