### ISSUE TITLE
kick from 1.19 on 1.18 server

### ISSUE THREAD

**Issue by TOWUK** [ViaVersion/ViaVersion#2916] opened 2022-06-07 17:34 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/5e6bf30f5e1a643f244f601bc5e3b5de3c3c4249dc8b3793e343aa6c90f5bf4d

### Console Error
https://paste.gg/p/anonymous/7dd2cfc9373f41929d88c6a92de3af3e

### Bug Description

kick from 1.19 on 1.18 server
/kill and u kick from server :0

papermc latest 1.18
latest STABLE viaversion (hour ago update plugin vrlocity) FROM GITHUB RELEASES: 07 june 2022 release

### Steps to Reproduce

join
/kill
u kicked from paper server

### Expected Behavior

none, fabric 1.19 latest client

### Additional Server Info

velocity latest
paper latest
ALL plugins latest versions!

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2022-06-07 17:34
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--377e6b66--b140%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--377e6b66--b140%29-3498db?style=flat-square) </br>![ViaVersion (4.3.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.0)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by Quantum64** [comment] 2022-06-07 18:29
Duplicate of #2915.

**Closed** 2022-06-07 20:46 UTC
Labels: Unconfirmed
