### ISSUE TITLE
Chat Messages sent in PlayerJoinEvent are broken

### ISSUE THREAD

**Issue by Outfluencer** [ViaVersion/ViaVersion#3785] opened 2024-04-12 12:20 UTC
### `/viaversion dump` Output

no dump

### Bug Description

If a player joins on the server and you send the player a message this appears in the chat instead of the message

this happens on 1.20.1 server when a 1.20.4 clients joins

![wOfEkOkO68](https://github.com/ViaVersion/ViaVersion/assets/48880402/3ed6b0d4-0de8-41d5-aa16-91707b9ad61c)

### Steps to Reproduce

Have a plugin that send a message on PlayerJoinEvent on an 1.20.1 server
Be behind a bungee instance or set the server to cracked (on premium spigot server it works as intended)
join the server with an 1.20.4 client

### Expected Behavior

Chat should not be broken

### Additional Server Info

I am using bungee but its broken on cracked spigot/paper as well

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2024-04-12 12:20
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kichura** [comment] 2024-04-12 12:34
Duplicate of #3438.

**Closed by Kichura** 2024-04-12 12:34 UTC
Labels: Unconfirmed
