### ISSUE TITLE
say test from console disconnects everybody, even 1.20.2 clients sometimes

### ISSUE THREAD

**Issue by mrfloris** [ViaVersion/ViaVersion#3560] opened 2023-12-07 03:33 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/d5620991f900b9339801dfbb6dc05d1fd45bb2ec67525e8d952053dc558eeb6d

### Console Error

```
> say test
[04:28:43 INFO]: [Not Secure] [Server] test
[04:28:44 INFO]: ender_vine lost connection: Disconnected
[04:28:44 INFO]: ender_vine left the game
>
```

### Bug Description

paper 1.20.2 server with latest jenkins viaversion and players join with 1.20.2 and 1.20.3, and when i type in console "say test" about 50% of the online players disconnect, which doesn't happen without viaversion installed. 

tested on stand alone paper jar with only plugin viaversion. and i can reproduce the issue

### Steps to Reproduce

throw paper jar in a dir
put viaversion jenkins in plugins
start the server, /stop and start again if you must
join with 1.20.3 client
type in console say test, and poof they're offline.

### Expected Behavior

expect them to get the msg, not disconnect

### Additional Server Info

live server:

```
> ver
[04:32:22 INFO]: Checking version, please wait...
[04:32:22 INFO]: This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version
Previous version: git-Paper-309 (MC: 1.20.2)
```
vv from jenkins build 477

test server, 
```
> ver
[04:32:07 INFO]: Checking version, please wait...
[04:32:07 INFO]: This server is running Paper version git-Paper-280 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 4675152)
You are 38 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
>
```
vv from jenkins build 476

happens in both live and test server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by mrfloris** [comment] 2023-12-07 03:39
Client log
```
[04:21:18] [Render thread/INFO]: Connecting to localhost, 33333
[04:21:19] [Render thread/INFO]: [System] [CHAT] ender_vine joined the game
[04:21:19] [Render thread/INFO]: Loaded 2 advancements
[04:21:24] [Render thread/WARN]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: te: Loading NBT data
[04:22:55] [Render thread/INFO]: Connecting to localhost, 33333
[04:22:56] [Render thread/INFO]: [System] [CHAT] ender_vine joined the game
[04:22:56] [Render thread/INFO]: Loaded 2 advancements
[04:23:04] [Render thread/WARN]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: te: Loading NBT data
```

client screenshot 

![image](https://github.com/ViaVersion/ViaVersion/assets/28841349/4cc8b6d7-02b4-4ae3-a357-9e1cee5f2e43)

**Comment by mrfloris** [comment] 2023-12-07 03:42
from the live server, an example
```
> say test
[04:14:33 INFO]: [Not Secure] [Server] test
[04:14:33 INFO]: BeastsongAmbles lost connection: Disconnected 
[04:14:33 INFO]: BeastsongAmbles [Elf]  left the game
[04:14:33 INFO]: KoolKidSimp lost connection: Disconnected 
[04:14:33 INFO]: ❊ KoolKidSimp [Elf]  left the game
[04:14:33 INFO]: Ardenwyn lost connection: Disconnected 
[04:14:33 INFO]: Ardenwyn [Elf]  left the game
[04:14:33 INFO]: acmaverick00 lost connection: Disconnected 
[04:14:33 INFO]: ❊ acmaverick00 [Elf]  left the game
```

**Comment by mrfloris** [comment] 2023-12-07 03:50
I did not spot this earlier, but I do now.. Could be duplicate of https://github.com/ViaVersion/ViaVersion/issues/3551

**Comment by Barvalg** [comment] 2023-12-07 04:33
![Platform: git--Paper--318%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--318%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Barvalg** [comment] 2023-12-07 04:36
![Platform: git--Paper--318%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--318%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by mrfloris** [comment] 2023-12-07 05:23
> ![Platform: git--Paper--318%20%28MC%3A%201.20.2%29](https://camo.githubusercontent.com/c3a3d7e56cbf477b618a57cfefad757542e5bd394642928b1ce8c95eceb85363/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d50617065722d2d3331382532302532384d43253341253230312e32302e322532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.9.2-SNAPSHOT): 1 commits behind master](https://camo.githubusercontent.com/6ba655be85dd771c86e8cfbc0cd090d48cf952d6b4ce93f72706e25738ad8b03/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e392e322d2d534e415053484f54292d31253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> 
> ### Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump

Already provided the test wit 746, nothing to update to.

**Comment by kennytv** [comment] 2023-12-07 08:58
duplicate of https://github.com/ViaVersion/ViaVersion/issues/3551

**Closed by kennytv** 2023-12-07 08:58 UTC
Labels: Unconfirmed
