### ISSUE TITLE
Bug Report viaversion

### ISSUE THREAD

**Issue by MrTokyo12345** [ViaVersion/ViaVersion#1721] opened 2020-04-13 00:53 UTC
**Describe the bug, provide any errors**
https://pastebin.com/dgjg5BU0

**How can we reproduce it?**
When I go into a 1.12 mode and after I do / hub it gives me these errors

**Screenshots**
https://ibb.co/t4Qx8HZ

**ViaVersion Dump:**
https://dump.viaversion.com/1674138e6eb827e43af4aac7c542ea1300431ffb8ea99326af1b21b03a056aec

**Additional server info**
Proxy flamecord

**Comment by creeper123123321** [comment] 2020-04-13 21:46
Duplicate of #1611

**Closed** 2020-04-13 22:01 UTC
