### ISSUE TITLE
[ViaVersion] ERROR IN Protocol1_19_1To1_19_3 IN REMAP OF PLAYER_INFO_UPDATE (0x36)

### ISSUE THREAD

**Issue by ttt0** [ViaVersion/ViaVersion#3513] opened 2023-10-30 18:24 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/6cd9f347637a2de3e99745274a9cc20467951eacd29d4060916d7cbaa3b934df

### Console Error

```
https://mclo.gs/L6W2fqG
```

### Bug Description

I don't know why

### Steps to Reproduce

I don't know why

### Expected Behavior

When this error is corrected, it does not take the player into the game.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2023-10-30 18:24
![Platform: git--Purpur--1933%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Purpur--1933%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by FormallyMyles** [comment] 2023-10-30 18:38
Duplicate of #3207

**Closed by FormallyMyles** 2023-10-30 18:38 UTC
Labels: Unconfirmed
