### ISSUE TITLE
Players can't join

### ISSUE THREAD

**Issue by bielik1** [ViaVersion/ViaVersion#3177] opened 2022-12-18 10:30 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/4dab1678d8811aa92d7cb63d657efe1cbea4c94e41be3f34a5f7928fb1cd6a2e

### Console Error

io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: DECLARE_RECIPES, Type: FlatVarIntItem Array, Data: [Pair{Type|VarInt, 835}, Pair{Type|String, minecraft:stripped_acacia_wood}, Pair{Type|String, crafting_shaped}, Pair{Type|VarInt, 2}, Pair{Type|VarInt, 2}, Pair{Type|String, bark}, Pair{Type|FlatVarIntItem Array, [Lcom.viaversion.viaversion.api.minecraft.item.Item;@7cd53e56}], Source 0: com.viaversion.viaversion.protocols.protocol1_13_1to1_13.packets.InventoryPackets$2 (Anonymous), Packet ID: 84
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: DECLARE_RECIPES, Type: FlatVarIntItem Array, Data: [Pair{Type|VarInt, 835}, Pair{Type|String, minecraft:stripped_acacia_wood}, Pair{Type|String, crafting_shaped}, Pair{Type|VarInt, 2}, Pair{Type|VarInt, 2}, Pair{Type|String, bark}, Pair{Type|FlatVarIntItem Array, [Lcom.viaversion.viaversion.api.minecraft.item.Item;@7cd53e56}], Source 0: com.viaversion.viaversion.protocols.protocol1_13_1to1_13.packets.InventoryPackets$2 (Anonymous), Packet ID: 84
Caused by: java.io.IOException: Expected root tag to be a CompoundTag, was 1
        at com.viaversion.viaversion.libs.opennbt.NBTIO.readTag(NBTIO.java:203) ~[?:?]
        at com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:53) ~[?:?]
        at com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:36) ~[?:?]
        at com.viaversion.viaversion.api.type.types.minecraft.FlatVarIntItemType.read(FlatVarIntItemType.java:44) ~[?:?]
        at com.viaversion.viaversion.api.type.types.minecraft.FlatVarIntItemType.read(FlatVarIntItemType.java:30) ~[?:?]
        at com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:49) ~[?:?]
        at com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:30) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:181) ~[?:?]
        at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.data.RecipeRewriter1_13_2.handleCraftingShaped(RecipeRewriter1_13_2.java:56) ~[?:?]
        at com.viaversion.viaversion.rewriter.RecipeRewriter.handle(RecipeRewriter.java:43) ~[?:?]
        at com.viaversion.viaversion.protocols.protocol1_13_1to1_13.packets.InventoryPackets$2.lambda$registerMap$0(InventoryPackets.java:90) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:249) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:49) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:31) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[server.jar:3.1.2-SNAPSHOT (git-2d072151-b185)]

### Bug Description

I have ViaVersion and ViaBackwards on my Velocity server as well as all my other servers and I can't access the server 
I've tried setting the minimum version to 1.13 and 1.13.1 but it doesn't work
Unistalling plugins doesn't change anything

### Steps to Reproduce

1.  Install Velocity
2. Install ViaVersion and ViaBackwards
4. Try to join the server

### Expected Behavior

Players should be able to join normally

### Additional Server Info

I've using Velocity wich: LibertyBans, PistonMotd, Skinrestorer

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2022-12-18 10:30
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--2d072151--b185%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--2d072151--b185%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment] 2022-12-18 20:58
Duplicate of https://github.com/ViaVersion/ViaVersion/issues/2383

**Closed by FormallyMyles** 2022-12-18 20:58 UTC
Labels: Unconfirmed
