### ISSUE TITLE
Invalid entity data item type stuck me with any clientside viaversion

### ISSUE THREAD

**Issue by Calvineries** [ViaVersion/ViaVersion#3315] opened 2023-05-08 07:04 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/ce9b84b0833dd8c81e4a6248df942c809676a4e9341aea3687a02b02344acfca

### Console Error

Here is full logs from my die to return to lobby :
https://paste.gg/p/anonymous/8757e338848845a7989f678802082d29/files/df455c6a59b946a0b6a017d04b0e595b/raw

### Bug Description

This issue occurs with ViaFabric and ViaFabricPlus.
I reported it to ViaFabricPlus, and the developer told me it's caused by ViaVersion and should be reported here.
(https://github.com/FlorianMichael/ViaFabricPlus/issues/83)

When you die in certain game modes on this server while using ViaFabric/ViaFabricPlus, you get stuck.
Console spam "Invalid entity data item type for field 8 on entity class_1295" until you return to the hub.

### Steps to Reproduce

0. Install ViaFabric or ViaFabricPlus
1. Join server "funcraft.net"
2. Join gamemode "Hikabrain" 1v1
3. When the game has started, die (by jumping in void or getting killed).
4. You are now stuck, you can't move.

### Expected Behavior

I should be able to move after respawn.

### Additional Server Info

i'm in 1.19.4, Funcraft is in 1.9.4 (to 1.11.2) and seem to not use ViaVersion.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2023-05-08 07:04
![Platform: 0.4.10+364--merge](https://img.shields.io/badge/Platform-0.4.10+364--merge-3498db?style=flat-square) </br>![ViaVersion (4.7.0-23w18a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.7.0--23w18a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment] 2023-05-20 20:56
Duplicate of [ViaFabric's #192](https://github.com/ViaVersion/ViaFabric/issues/192).

**Closed by Kichura** 2023-05-20 20:56 UTC
Labels: Unconfirmed
