### ISSUE TITLE
Everybody is stuck when a new player joins

### ISSUE THREAD

**Issue by KhrysAK47** [ViaVersion/ViaVersion#2213] opened 2020-11-27 16:10 UTC
**Describe the bug, provide any errors**
I'm using ViaVersion (latest) along with IridiumSkyblock (latest), and when I'm in the Islands world, when a new player joins, all players are stuck under ground (video below), this only happens when ViaVersion is 3.2.0, also asked the developer of IridiumSkyblock and it's definitely a issue with ViaVersion, because when I downgraded to ViaVersion 3.1.1 this issue stopped happening. 

**How can we reproduce it?**
1. Have IridiumSkyblock (latest) and ViaVersion (latest) installed on your PaperSpigot 1.8.8 Server.
2. Open Minecraft 1.16.3 or 1.16.4
3. Join the server with a account and create a island (/is).
4. Open another minecraft and join the same server
5. Boom, the first minecraft account is stuck under ground

**Expected behaviour**
Well the only thing that is not supposed to happen is every player getting stuck when a new player joins when using latest ViaVersion. Rest is fine.

**Screenshots**
Here we can see a new player joining, and I got stuck without doing anything. https://www.youtube.com/watch?v=2VFd50diW-A

**ViaVersion Dump**
https://dump.viaversion.com/16b1c748b25024399c400b115b5174a83ea8761c8f7fca1d6efa2cab08ceb976

**Additional server info**
Server is running a base of PaperSpigot 1.8.8.

**Checklist**
- [X] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KhrysAK47** [comment] 2020-11-27 16:13
I would like to also point out this issue is very similar: https://github.com/ViaVersion/ViaVersion/issues/1438 and still didn't get a fix.

**Comment by KennyTV** [comment] 2020-11-27 16:16
No need to open a new issue if it has already been reported. :p
Duplicate of #1438

**Closed by KennyTV** 2020-11-27 16:16 UTC
