### ISSUE TITLE
Error + disconnect when using GSit's /sit command on 1.18 server with 1.8 client

### ISSUE THREAD

**Issue by MedicOP** [ViaVersion/ViaVersion#2818] opened 2022-02-06 22:09 UTC
### `/viaversion dump` Output

https://pastebin.com/raw/E2D2Tfq0

### Console Error

(https://paste.gg/p/anonymous/3599fc898ecd4050b886692f984f895a/files/4e13539c73fe461d9f412147a34c50b4/raw)

### Bug Description

Error + disconnect when using GSit's /sit command on 1.18 server with 1.8 client

### Steps to Reproduce

1. Install GSit plugin on 1.18 server
2. Use /sit on a 1.8 client
3. Get kicked from server

### Expected Behavior

It should show the player sitting which works fine on 1.18 client

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2022-02-06 22:09
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FormallyMyles** [comment] 2022-02-06 22:20
Based on your stacktrace this is down to "at me.levansj01.verus.util.viaversion.V1_17Remapper$2.lambda$registerMap$0(Unknown Source)" and can't be fixed by us (I have no idea what that remapper does).

**Closed by FormallyMyles** 2022-02-06 22:20 UTC
Labels: Unconfirmed

**Comment by Kichura** [comment] 2022-02-06 22:33
Caused by verus anti-cheat's viaversion compatibility code - You will have to ask those guys to fix it instead as it isn't caused by this plugin.

**Comment by MedicOP** [comment] 2022-02-06 22:59
Alright thanks
