### ISSUE TITLE
Console error and my users cannot log in sometimes due to this

### ISSUE THREAD

**Issue by Shiade** [ViaVersion/ViaVersion#1864] opened 2020-06-30 20:25 UTC
**Describe the bug, provide any errors**
This is something that has not happened to me before and it just happened out of the blue, sometimes the plugin starts sending this error to the console and does not let anyone in, I don't know what is happening

https://hastebin.com/yavitoqaso.cs
https://hastebin.com/ovigefaguv.bash

**How can we reproduce it?**
1. Login on 1.12'
3. The '....' is displayed wrong

**Expected behaviour**
That this error does not appear on the console and that my players can play well

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/ae770d68dc15c548384bc3f5e4f0489cccf629348d25e90871e6b8c6f17aa7b4

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I use more than 30 plugins, the base version of my server is 1.12.2 (Paper), I use the three plugins too: ViaBackwards, ViaRewind and ViaVersion

**Comment by KennyTV** [comment] 2020-06-30 20:34
Duplicate of #https://github.com/ViaVersion/ViaVersion/issues/1860

**Closed by KennyTV** 2020-06-30 20:34 UTC
