### ISSUE TITLE
TabList cells are mixed

### ISSUE THREAD

**Issue by P3ridot** [ViaVersion/ViaVersion#3186] opened 2022-12-26 21:37 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/6fa32ecbecf332464e35ac0902217c33eaa00d3cd0083949e5604a5e31d85438

### Bug Description

TabList cells on 1.19.3 clients are mixed, on 1.19.2 clients everything works normal. It's normally probably hard to notice, but I'm using plugin to display data on tablist instead actual players.

1.19.2 client:
![image](https://user-images.githubusercontent.com/28200355/209584290-cfa1c174-85e5-4030-8170-3fcc391a1f93.png)

1.19.3 client:
![image](https://user-images.githubusercontent.com/28200355/209584299-a9208f89-12be-4fbc-9ae0-ad59c0ab9b3f.png)

### Steps to Reproduce

1. Run 1.8-1.19.2 Server with ViaVersion installed
2. Join server with 1.19.2 client - everything works normal
3. Join server with 1.19.3 client - tablist cells are in wrong order

### Expected Behavior

TabList cells order should be preserved on 1.19.3 clients

### Additional Server Info

I'm using Paper 1.12.2, but same problem appears on newer/olders versions (even on base 1.19.2). Plugin that modifies tablist cells is this https://github.com/FunnyGuilds/FunnyGuilds and I'm developer of it - if any additional info would be required I can help.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2022-12-26 21:38
![Platform: git--Paper--1618%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by kennytv** [comment] 2022-12-27 08:15
What happens with the plugin on a 1.19.3 server? The way the client sorts the entries might have been changed, which wouldn't really be anything we can do much about

**Comment by Kichura** [comment] 2022-12-27 10:49
From what i can see; TabList hides npcs properly in 1.19.2 whereas 1.19.3 reveals them entirely.

Assuming this is what OP's subject is.

**Comment by P3ridot** [comment] 2022-12-27 15:28
> What happens with the plugin on a 1.19.3 server? The way the client sorts the entries might have been changed, which wouldn't really be anything we can't do much about

We recently added support for 1.19.3 and everything works fine:

Paper 1.19.3, 1.19.3 client and without any other plugins except FunnyGuilds:
![image](https://user-images.githubusercontent.com/28200355/209687650-5e25f184-3698-472a-90b3-aa4434dc5a02.png)

**Comment by FlorianMichael** [comment] 2023-03-15 12:16
Yes, I can confirm that from 1.19.2 -> 1.19.3 the tablist sorting is changed, and now a different list is used, this causes the tablist cells to be broken on a 1.19.3 client, here is the clientside change:
https://github.com/FlorianMichael/ViaFabricPlus/blob/3303d975b3985ec45e1b18dc1362d9d0b57e8acb/src/main/java/de/florianmichael/viafabricplus/injection/mixin/fixes/MixinClientPlayNetworkHandler.java#L73

**Comment by FlorianMichael** [comment] 2024-12-15 13:18
Valid issue but cannot and most likely will not get fixed on VV due to the huge work this would need.

**Closed by FlorianMichael** 2024-12-15 13:18 UTC
Labels: Bug
